/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.automation.bolt.gui;

import static com.automation.bolt.common.killProcess;
import static com.automation.bolt.gui.CreateAPITest.saveTestFileWhileClosingTheWindow;
import static com.automation.bolt.gui.EditAPITest.saveTestSuitWhenWindowIsGettingClosed;
import static com.automation.bolt.gui.TestReporting.treeTestReporting;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

import com.automation.bolt.constants;
import com.automation.bolt.renderer.JTreeCellRenderer;

/**
 *
 * @author zakir
 */
public class ApiTestRunner extends javax.swing.JFrame {
    public EditRegressionSuite editTestSuite = new EditRegressionSuite();
    public EditAPITest editApiTest = new EditAPITest();
    public ExecuteApiTest runApiTest = new ExecuteApiTest();
    public ExecuteRegressionSuite runTestSuite = new ExecuteRegressionSuite();
    public CreateTestSuite createTestSuite = new CreateTestSuite();
    public CreateAPITest createApiTestSuite = new CreateAPITest();
    public SSLCertificate sslCertConfig = new SSLCertificate();
    public TestReporting testReporting = new TestReporting();
    public SettingsAndConfiguration settingsAndConfiguration = new SettingsAndConfiguration(); 
    public static String bttnAPIBackColor;
    public static String userDir=System.getProperty("user.dir");
    //public AddEnvVariableList addEnvVariableList = new AddEnvVariableList();
    //public static Image titleIcon = Toolkit.getDefaultToolkit().getImage(constants.userDir+"C:\\Users\\zakir\\Documents\\bolt.jpg");
    /**
     * Creates new form AutomationTestRunner
     */
    public ApiTestRunner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBolt = new javax.swing.JPanel();
        lblBolt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMenuBarGUI = new javax.swing.JPanel();
        pnlCreateTestSuite = new javax.swing.JPanel();
        lblCreateTestSuite = new javax.swing.JLabel();
        pnlEditTestSuite = new javax.swing.JPanel();
        lblEditTestSuite = new javax.swing.JLabel();
        pnlExecuteTestSuite = new javax.swing.JPanel();
        lblExecuteTestSuite = new javax.swing.JLabel();
        pnlAutomationTestReport = new javax.swing.JPanel();
        lblAutomationTestReport = new javax.swing.JLabel();
        lblSettingsAndConfiguration = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(955, 258));
        setName("tab"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(955, 258));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlBolt.setBackground(new java.awt.Color(51, 51, 51));
        pnlBolt.setMinimumSize(new java.awt.Dimension(708, 115));

        lblBolt.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 69)); // NOI18N
        lblBolt.setForeground(new java.awt.Color(153, 102, 255));
        lblBolt.setText("Phantom");
        lblBolt.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir").replaceAll("\\\\", "/")+"/icons/Phantom.png"));

            jLabel2.setBackground(new java.awt.Color(255, 255, 255));
            jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 9)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setText("API  T e s t  A c c e l e r a t o r . . . ");

            pnlMenuBarGUI.setBackground(new java.awt.Color(51, 51, 51));
            pnlMenuBarGUI.setOpaque(false);

            pnlCreateTestSuite.setBackground(new java.awt.Color(0, 0, 0));
            pnlCreateTestSuite.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    pnlCreateTestSuiteMouseClicked(evt);
                }
            });

            lblCreateTestSuite.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
            lblCreateTestSuite.setForeground(new java.awt.Color(255, 255, 255));
            lblCreateTestSuite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblCreateTestSuite.setText("Write API Test");
            lblCreateTestSuite.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
            lblCreateTestSuite.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    lblCreateTestSuiteMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    lblCreateTestSuiteMouseExited(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    lblCreateTestSuiteMousePressed(evt);
                }
            });

            javax.swing.GroupLayout pnlCreateTestSuiteLayout = new javax.swing.GroupLayout(pnlCreateTestSuite);
            pnlCreateTestSuite.setLayout(pnlCreateTestSuiteLayout);
            pnlCreateTestSuiteLayout.setHorizontalGroup(
                pnlCreateTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCreateTestSuiteLayout.createSequentialGroup()
                    .addComponent(lblCreateTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            pnlCreateTestSuiteLayout.setVerticalGroup(
                pnlCreateTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblCreateTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            );

            pnlEditTestSuite.setBackground(new java.awt.Color(0, 0, 0));
            pnlEditTestSuite.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    pnlEditTestSuiteMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    pnlEditTestSuiteMouseExited(evt);
                }
            });

            lblEditTestSuite.setBackground(new java.awt.Color(204, 204, 255));
            lblEditTestSuite.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
            lblEditTestSuite.setForeground(new java.awt.Color(255, 255, 255));
            lblEditTestSuite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblEditTestSuite.setText("Edit API Test");
            lblEditTestSuite.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
            lblEditTestSuite.setMaximumSize(new java.awt.Dimension(163, 32));
            lblEditTestSuite.setMinimumSize(new java.awt.Dimension(163, 32));
            lblEditTestSuite.setPreferredSize(new java.awt.Dimension(163, 32));
            lblEditTestSuite.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    lblEditTestSuiteMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    lblEditTestSuiteMouseExited(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    lblEditTestSuiteMousePressed(evt);
                }
            });

            javax.swing.GroupLayout pnlEditTestSuiteLayout = new javax.swing.GroupLayout(pnlEditTestSuite);
            pnlEditTestSuite.setLayout(pnlEditTestSuiteLayout);
            pnlEditTestSuiteLayout.setHorizontalGroup(
                pnlEditTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblEditTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            );
            pnlEditTestSuiteLayout.setVerticalGroup(
                pnlEditTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblEditTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pnlExecuteTestSuite.setBackground(new java.awt.Color(0, 0, 0));

            lblExecuteTestSuite.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
            lblExecuteTestSuite.setForeground(new java.awt.Color(255, 255, 255));
            lblExecuteTestSuite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblExecuteTestSuite.setText("Run API Test");
            lblExecuteTestSuite.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblExecuteTestSuite.setFocusable(false);
            lblExecuteTestSuite.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    lblExecuteTestSuiteMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    lblExecuteTestSuiteMouseExited(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    lblExecuteTestSuiteMousePressed(evt);
                }
            });

            javax.swing.GroupLayout pnlExecuteTestSuiteLayout = new javax.swing.GroupLayout(pnlExecuteTestSuite);
            pnlExecuteTestSuite.setLayout(pnlExecuteTestSuiteLayout);
            pnlExecuteTestSuiteLayout.setHorizontalGroup(
                pnlExecuteTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblExecuteTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            pnlExecuteTestSuiteLayout.setVerticalGroup(
                pnlExecuteTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExecuteTestSuiteLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblExecuteTestSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            pnlAutomationTestReport.setBackground(new java.awt.Color(0, 0, 0));

            lblAutomationTestReport.setFont(new java.awt.Font("OCR A Extended", 0, 16)); // NOI18N
            lblAutomationTestReport.setForeground(new java.awt.Color(255, 255, 255));
            lblAutomationTestReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblAutomationTestReport.setText("API Test Report");
            lblAutomationTestReport.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    lblAutomationTestReportMouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    lblAutomationTestReportMouseExited(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    lblAutomationTestReportMousePressed(evt);
                }
            });

            javax.swing.GroupLayout pnlAutomationTestReportLayout = new javax.swing.GroupLayout(pnlAutomationTestReport);
            pnlAutomationTestReport.setLayout(pnlAutomationTestReportLayout);
            pnlAutomationTestReportLayout.setHorizontalGroup(
                pnlAutomationTestReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblAutomationTestReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            pnlAutomationTestReportLayout.setVerticalGroup(
                pnlAutomationTestReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblAutomationTestReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            );

            lblSettingsAndConfiguration.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir").replaceAll("\\\\", "/")+"/icons/settingAndConfiguration.png"));
                lblSettingsAndConfiguration.setToolTipText("Setting & Configuration");
                lblSettingsAndConfiguration.setFocusable(false);
                lblSettingsAndConfiguration.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        lblSettingsAndConfigurationMousePressed(evt);
                    }
                });

                javax.swing.GroupLayout pnlMenuBarGUILayout = new javax.swing.GroupLayout(pnlMenuBarGUI);
                pnlMenuBarGUI.setLayout(pnlMenuBarGUILayout);
                pnlMenuBarGUILayout.setHorizontalGroup(
                    pnlMenuBarGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuBarGUILayout.createSequentialGroup()
                        .addGroup(pnlMenuBarGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlCreateTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlEditTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlExecuteTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlAutomationTestReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlMenuBarGUILayout.createSequentialGroup()
                                .addComponent(lblSettingsAndConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                );
                pnlMenuBarGUILayout.setVerticalGroup(
                    pnlMenuBarGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuBarGUILayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblSettingsAndConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlCreateTestSuite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnlEditTestSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnlExecuteTestSuite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnlAutomationTestReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                );

                javax.swing.GroupLayout pnlBoltLayout = new javax.swing.GroupLayout(pnlBolt);
                pnlBolt.setLayout(pnlBoltLayout);
                pnlBoltLayout.setHorizontalGroup(
                    pnlBoltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBoltLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(pnlBoltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBolt)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(pnlMenuBarGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                pnlBoltLayout.setVerticalGroup(
                    pnlBoltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenuBarGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBoltLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBolt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(88, 88, 88))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pnlBolt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBolt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                );

                setSize(new java.awt.Dimension(846, 295));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Image titleIcon = Toolkit.getDefaultToolkit().getImage(constants.userDir+"\\icons\\Phantom2.png");
        this.setIconImage(titleIcon);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //System.out.println(tabbedPaneMenuBar.getTabComponentAt(WIDTH).getName());
    }//GEN-LAST:event_formWindowActivated

    private void lblAutomationTestReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAutomationTestReportMouseExited
        pnlAutomationTestReport.setBackground(new Color(0,0,0));
        lblAutomationTestReport.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_lblAutomationTestReportMouseExited

    private void lblAutomationTestReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAutomationTestReportMouseEntered
        pnlAutomationTestReport.setBackground(new java.awt.Color(203, 67, 53));
        lblAutomationTestReport.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_lblAutomationTestReportMouseEntered

    private void lblExecuteTestSuiteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExecuteTestSuiteMousePressed
        //if(lblExecuteTestSuite.getText().contentEquals("Execute Test Suite")){
            //runTestSuite.setLocationRelativeTo(null);
            //runTestSuite.setVisible(true);
        //}else if(lblExecuteTestSuite.getText().contentEquals("Execute API Test")){
            //runApiTest.setLocationRelativeTo(null);
            runApiTest.setVisible(true);
            //if(addEnvVariableList.isVisible())
                //addEnvVariableList.dispose();
        //}
    }//GEN-LAST:event_lblExecuteTestSuiteMousePressed

    private void lblExecuteTestSuiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExecuteTestSuiteMouseExited
        pnlExecuteTestSuite.setBackground(new Color(0,0,0));
        lblExecuteTestSuite.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_lblExecuteTestSuiteMouseExited

    private void lblExecuteTestSuiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExecuteTestSuiteMouseEntered
        pnlExecuteTestSuite.setBackground(new java.awt.Color(203, 67, 53));
        lblExecuteTestSuite.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_lblExecuteTestSuiteMouseEntered

    private void pnlEditTestSuiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditTestSuiteMouseExited
        //pnlEditTestSuite.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_pnlEditTestSuiteMouseExited

    private void pnlEditTestSuiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditTestSuiteMouseEntered
        //pnlEditTestSuite.setBackground(java.awt.Color.pink);
    }//GEN-LAST:event_pnlEditTestSuiteMouseEntered

    private void lblEditTestSuiteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditTestSuiteMousePressed
        //if(lblEditTestSuite.getText().contentEquals("Edit Test Suite")){
            //editTestSuite.setLocationRelativeTo(null);
            //editTestSuite.setVisible(true);
        //}else if(lblEditTestSuite.getText().contentEquals("Edit API Test")){
            //createApiTestSuite.setLocationRelativeTo(null);
            editApiTest.setVisible(true);
            //if(addEnvVariableList.isVisible())
                //addEnvVariableList.dispose();
        //}
    }//GEN-LAST:event_lblEditTestSuiteMousePressed

    private void lblEditTestSuiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditTestSuiteMouseExited
        pnlEditTestSuite.setBackground(new Color(0,0,0));
        lblEditTestSuite.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_lblEditTestSuiteMouseExited

    private void lblEditTestSuiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditTestSuiteMouseEntered
        pnlEditTestSuite.setBackground(new java.awt.Color(203, 67, 53));
        lblEditTestSuite.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_lblEditTestSuiteMouseEntered

    private void pnlCreateTestSuiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCreateTestSuiteMouseClicked

    }//GEN-LAST:event_pnlCreateTestSuiteMouseClicked

    private void lblCreateTestSuiteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateTestSuiteMousePressed
        //if(lblCreateTestSuite.getText().contentEquals("Build Test Suite")){
            //createTestSuite.setLocationRelativeTo(null);
            //createTestSuite.setVisible(true);
        //}else if(lblCreateTestSuite.getText().contentEquals("Build API Test")){
            //createApiTestSuite.setLocationRelativeTo(null);
            createApiTestSuite.setVisible(true);
            //if(addEnvVariableList.isVisible())
                //addEnvVariableList.dispose();
        //}
    }//GEN-LAST:event_lblCreateTestSuiteMousePressed

    private void lblCreateTestSuiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateTestSuiteMouseExited
        pnlCreateTestSuite.setBackground(new Color(0,0,0));
        lblCreateTestSuite.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_lblCreateTestSuiteMouseExited

    private void lblCreateTestSuiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateTestSuiteMouseEntered
        pnlCreateTestSuite.setBackground(new java.awt.Color(203, 67, 53));
        lblCreateTestSuite.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_lblCreateTestSuiteMouseEntered

    private void lblSettingsAndConfigurationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsAndConfigurationMousePressed
        if(lblSettingsAndConfiguration.isEnabled()){
            sslCertConfig.setLocationRelativeTo(null);
            sslCertConfig.setVisible(true);
        }
        //settingsAndConfiguration.setLocationRelativeTo(null);
        //settingsAndConfiguration.setVisible(true);
    }//GEN-LAST:event_lblSettingsAndConfigurationMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //if(addEnvVariableList.isVisible())
            //addEnvVariableList.dispose();
        
        if(sslCertConfig.isVisible())
            sslCertConfig.dispose();
        
        if(editTestSuite.isVisible())
            editTestSuite.dispose();
        
        if(runTestSuite.isVisible())
            runTestSuite.dispose();
        
        if(createTestSuite.isVisible())
            createTestSuite.dispose();
        
        if(testReporting.isVisible())
            testReporting.dispose();
        
        if(createApiTestSuite.isVisible())
            createApiTestSuite.dispose();
        
        if(editApiTest.isVisible())
            editApiTest.dispose();
        
        if(runApiTest.isVisible())
            runApiTest.dispose();
        
    }//GEN-LAST:event_formWindowClosed

    private void lblAutomationTestReportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAutomationTestReportMousePressed
        if(lblAutomationTestReport.getText().contentEquals("Automation Test Report")){
            Image titleIcon = Toolkit.getDefaultToolkit().getImage(constants.userDir+"\\icons\\bolt.jpg");
            testReporting.setIconImage(titleIcon);

            JTreeCellRenderer renderer = new JTreeCellRenderer();
            treeTestReporting.setCellRenderer(renderer);
            
            testReporting.setLocationRelativeTo(null);
            testReporting.setVisible(true);
        }
    }//GEN-LAST:event_lblAutomationTestReportMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        killProcess("chromedriver.exe");
        killProcess("msedgedriver.exe");
        
        if(editApiTest.isVisible())
            saveTestSuitWhenWindowIsGettingClosed();
        
        if(createApiTestSuite.isVisible())
            saveTestFileWhileClosingTheWindow();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApiTestRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApiTestRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApiTestRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApiTestRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ApiTestRunner().setLocationRelativeTo(null);
            new ApiTestRunner().setVisible(true);
            //MarqueeLabel myLable = new MarqueeLabel("Welcome to www.How2Java.com", MarqueeLabel.RIGHT_TO_LEFT, 20); 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel lblAutomationTestReport;
    public static javax.swing.JLabel lblBolt;
    public static javax.swing.JLabel lblCreateTestSuite;
    public static javax.swing.JLabel lblEditTestSuite;
    public static javax.swing.JLabel lblExecuteTestSuite;
    public static javax.swing.JLabel lblSettingsAndConfiguration;
    public static javax.swing.JPanel pnlAutomationTestReport;
    public static javax.swing.JPanel pnlBolt;
    public static javax.swing.JPanel pnlCreateTestSuite;
    public static javax.swing.JPanel pnlEditTestSuite;
    public static javax.swing.JPanel pnlExecuteTestSuite;
    public static javax.swing.JPanel pnlMenuBarGUI;
    // End of variables declaration//GEN-END:variables
}
