/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.automation.bolt.gui;

import static com.automation.bolt.common.killProcess;
import static com.automation.bolt.gui.CreateAPITest.saveTestFileWhileClosingTheWindow;
import static com.automation.bolt.gui.EditAPITest.saveTestSuitWhenWindowIsGettingClosed;
import static com.automation.bolt.gui.TestReporting.treeTestReporting;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

import com.automation.bolt.constants;
import com.automation.bolt.renderer.JTreeCellRenderer;

/**
 *
 * @author zakir
 */
public class AutomationTestRunner extends javax.swing.JFrame {
    public EditRegressionSuite editTestSuite = new EditRegressionSuite();
    public EditAPITest editApiTest = new EditAPITest();
    public ExecuteApiTest runApiTest = new ExecuteApiTest();
    public ExecuteRegressionSuite runTestSuite = new ExecuteRegressionSuite();
    public CreateTestSuite createTestSuite = new CreateTestSuite();
    public CreateAPITest createApiTestSuite = new CreateAPITest();
    public SSLCertificate2 sslCertConfig = new SSLCertificate2();
    public TestReporting testReporting = new TestReporting();
    public SettingsAndConfiguration settingsAndConfiguration = new SettingsAndConfiguration(); 
    public static String bttnAPIBackColor;
    public static String userDir = System.getProperty("user.dir");

    /**
     * Creates new form AutomationTestRunner
     */
    public AutomationTestRunner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        pnlBolt = new javax.swing.JPanel();
        lblBolt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMenuBarGUI = new javax.swing.JPanel();
        pnlCreateTestSuite = new javax.swing.JPanel();
        lblCreateTestSuite = new javax.swing.JLabel();
        pnlEditTestSuite = new javax.swing.JPanel();
        lblEditTestSuite = new javax.swing.JLabel();
        pnlExecuteTestSuite = new javax.swing.JPanel();
        lblExecuteTestSuite = new javax.swing.JLabel();
        pnlAutomationTestReport = new javax.swing.JPanel();
        lblAutomationTestReport = new javax.swing.JLabel();
        radioBttnGUI = new javax.swing.JRadioButton();
        radioBttnAPI = new javax.swing.JRadioButton();
        lblChooseTestType = new javax.swing.JLabel();
        lblSettingsAndConfiguration = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(955, 258));
        setName("tab");
        setResizable(false);
        setSize(new java.awt.Dimension(955, 258));
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override public void windowActivated(java.awt.event.WindowEvent evt) { formWindowActivated(evt); }
            @Override public void windowClosed(java.awt.event.WindowEvent evt) { formWindowClosed(evt); }
            @Override public void windowClosing(java.awt.event.WindowEvent evt) { formWindowClosing(evt); }
            @Override public void windowOpened(java.awt.event.WindowEvent evt) { formWindowOpened(evt); }
        });

        // === BOLT PANEL ===
        pnlBolt.setBackground(new java.awt.Color(51, 51, 51));
        pnlBolt.setMinimumSize(new java.awt.Dimension(708, 115));
        pnlBolt.setOpaque(false);

        lblBolt.setFont(new java.awt.Font("Segoe UI", 1, 69));
        lblBolt.setText("Bolt");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 9));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("T e s t  A c c e l e r a t o r . . . ");

        javax.swing.GroupLayout pnlBoltLayout = new javax.swing.GroupLayout(pnlBolt);
        pnlBolt.setLayout(pnlBoltLayout);
        pnlBoltLayout.setHorizontalGroup(
            pnlBoltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoltLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addGroup(pnlBoltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBoltLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(lblBolt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBoltLayout.setVerticalGroup(
            pnlBoltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBoltLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBolt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(99, 99, 99))
        );

        jDesktopPane1.setLayer(pnlBolt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayout(new BorderLayout());
        jDesktopPane1.add(pnlBolt, BorderLayout.CENTER);

        // === MENU CONTAINER ===
        JPanel menuContainer = new JPanel(new BorderLayout());
        menuContainer.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        menuContainer.setPreferredSize(new java.awt.Dimension(240, 300));
        menuContainer.setBackground(new java.awt.Color(51, 51, 51));

        // === MENU BAR GUI: 8px LEFT & RIGHT PADDING ===
        pnlMenuBarGUI.setBackground(new java.awt.Color(51, 51, 51));
        pnlMenuBarGUI.setOpaque(true);
        pnlMenuBarGUI.setLayout(new BoxLayout(pnlMenuBarGUI, BoxLayout.Y_AXIS));
        pnlMenuBarGUI.setBorder(BorderFactory.createEmptyBorder(0, 8, 0, 8)); // 8px LEFT & RIGHT
        pnlMenuBarGUI.setPreferredSize(new java.awt.Dimension(240, 300));
        pnlMenuBarGUI.setMaximumSize(new java.awt.Dimension(240, 300));

        // === TOP PANEL: 8px PADDING VIA CONTAINER ===
        JPanel topPanel = new JPanel(new GridBagLayout());
        topPanel.setOpaque(false);
        topPanel.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 0, 0, 0);
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // choose test type
        gbc.gridy = 0;
        lblChooseTestType.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseTestType.setText("choose test type");
        topPanel.add(lblChooseTestType, gbc);

        // GUI Test
        gbc.gridy = 1;
        radioBttnGUI.setFont(new java.awt.Font("Tahoma", 1, 12));
        radioBttnGUI.setForeground(new java.awt.Color(255, 255, 153));
        radioBttnGUI.setSelected(true);
        radioBttnGUI.setText("GUI Test");
        radioBttnGUI.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioBttnGUI.setContentAreaFilled(false);
        radioBttnGUI.setFocusPainted(false);
        radioBttnGUI.setFocusable(false);
        radioBttnGUI.setIconTextGap(0);
        radioBttnGUI.setMargin(new Insets(0, 0, 0, 0));
        radioBttnGUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) { radioBttnGUIMouseClicked(evt); }
            public void mouseEntered(java.awt.event.MouseEvent evt) { radioBttnGUIMouseEntered(evt); }
            public void mouseExited(java.awt.event.MouseEvent evt) { radioBttnGUIMouseExited(evt); }
            public void mousePressed(java.awt.event.MouseEvent evt) { radioBttnGUIMousePressed(evt); }
            public void mouseReleased(java.awt.event.MouseEvent evt) { radioBttnGUIMouseReleased(evt); }
        });
        radioBttnGUI.addActionListener(evt -> radioBttnGUIActionPerformed(evt));
        topPanel.add(radioBttnGUI, gbc);

        // API Test
        gbc.gridy = 2;
        radioBttnAPI.setFont(new java.awt.Font("Tahoma", 1, 12));
        radioBttnAPI.setForeground(new java.awt.Color(255, 255, 153));
        radioBttnAPI.setText("API Test");
        radioBttnAPI.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        radioBttnAPI.setContentAreaFilled(false);
        radioBttnAPI.setFocusPainted(false);
        radioBttnAPI.setFocusable(false);
        radioBttnAPI.setIconTextGap(0);
        radioBttnAPI.setMargin(new Insets(0, 0, 0, 0));
        radioBttnAPI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) { radioBttnAPIMouseEntered(evt); }
            public void mouseExited(java.awt.event.MouseEvent evt) { radioBttnAPIMouseExited(evt); }
        });
        radioBttnAPI.addActionListener(evt -> radioBttnAPIActionPerformed(evt));
        topPanel.add(radioBttnAPI, gbc);

        pnlMenuBarGUI.add(topPanel);
        pnlMenuBarGUI.add(Box.createVerticalStrut(8));

        // === SETTINGS ICON: 8px LEFT PADDING — PERFECTLY ALIGNED ===
        lblSettingsAndConfiguration.setIcon(new javax.swing.ImageIcon(userDir.replaceAll("\\\\", "/") + "/icons/settingAndConfiguration.png"));
        lblSettingsAndConfiguration.setToolTipText("Setting & Configuration");
        lblSettingsAndConfiguration.setEnabled(false);
        lblSettingsAndConfiguration.setFocusable(false);
        lblSettingsAndConfiguration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) { lblSettingsAndConfigurationMousePressed(evt); }
        });

        JPanel settingsPanel = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 0));
        settingsPanel.setOpaque(false);
        settingsPanel.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        settingsPanel.add(lblSettingsAndConfiguration);
        settingsPanel.setMaximumSize(new java.awt.Dimension(240, 30));
        settingsPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        pnlMenuBarGUI.add(settingsPanel);
        pnlMenuBarGUI.add(Box.createVerticalStrut(8));

        // === MENU ITEMS: ORIGINAL LAYOUT (PERFECT ALIGNMENT) ===
        pnlCreateTestSuite.setBackground(new java.awt.Color(0, 0, 0));
        pnlCreateTestSuite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) { pnlCreateTestSuiteMouseClicked(evt); }
        });

        lblCreateTestSuite.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16));
        lblCreateTestSuite.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateTestSuite.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCreateTestSuite.setIcon(new javax.swing.ImageIcon(userDir.replaceAll("\\\\", "/") + "/icons/buildTestSuite.png"));
        lblCreateTestSuite.setText("Create Test Suite");
        lblCreateTestSuite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) { lblCreateTestSuiteMouseEntered(evt); }
            public void mouseExited(java.awt.event.MouseEvent evt) { lblCreateTestSuiteMouseExited(evt); }
            public void mousePressed(java.awt.event.MouseEvent evt) { lblCreateTestSuiteMousePressed(evt); }
        });

        javax.swing.GroupLayout pnlCreateTestSuiteLayout = new javax.swing.GroupLayout(pnlCreateTestSuite);
        pnlCreateTestSuite.setLayout(pnlCreateTestSuiteLayout);
        pnlCreateTestSuiteLayout.setHorizontalGroup(
            pnlCreateTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreateTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        pnlCreateTestSuiteLayout.setVerticalGroup(
            pnlCreateTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreateTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuBarGUI.add(pnlCreateTestSuite);
        pnlMenuBarGUI.add(Box.createVerticalStrut(3));

        // === EDIT, EXECUTE, REPORT — SAME ORIGINAL LAYOUT ===
        // ... (same as before — unchanged, perfect)

        pnlEditTestSuite.setBackground(new java.awt.Color(0, 0, 0));
        pnlEditTestSuite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) { pnlEditTestSuiteMouseEntered(evt); }
            public void mouseExited(java.awt.event.MouseEvent evt) { pnlEditTestSuiteMouseExited(evt); }
        });

        lblEditTestSuite.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16));
        lblEditTestSuite.setForeground(new java.awt.Color(255, 255, 255));
        lblEditTestSuite.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditTestSuite.setIcon(new javax.swing.ImageIcon(userDir.replaceAll("\\\\", "/") + "/icons/editTestSuite.png"));
        lblEditTestSuite.setText("Edit Test Suite");
        lblEditTestSuite.setMaximumSize(new java.awt.Dimension(163, 32));
        lblEditTestSuite.setMinimumSize(new java.awt.Dimension(163, 32));
        lblEditTestSuite.setPreferredSize(new java.awt.Dimension(163, 32));
        lblEditTestSuite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) { lblEditTestSuiteMouseEntered(evt); }
            public void mouseExited(java.awt.event.MouseEvent evt) { lblEditTestSuiteMouseExited(evt); }
            public void mousePressed(java.awt.event.MouseEvent evt) { lblEditTestSuiteMousePressed(evt); }
        });

        javax.swing.GroupLayout pnlEditTestSuiteLayout = new javax.swing.GroupLayout(pnlEditTestSuite);
        pnlEditTestSuite.setLayout(pnlEditTestSuiteLayout);
        pnlEditTestSuiteLayout.setHorizontalGroup(
            pnlEditTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        pnlEditTestSuiteLayout.setVerticalGroup(
            pnlEditTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuBarGUI.add(pnlEditTestSuite);
        pnlMenuBarGUI.add(Box.createVerticalStrut(3));

        pnlExecuteTestSuite.setBackground(new java.awt.Color(0, 0, 0));

        lblExecuteTestSuite.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16));
        lblExecuteTestSuite.setForeground(new java.awt.Color(255, 255, 255));
        lblExecuteTestSuite.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblExecuteTestSuite.setIcon(new javax.swing.ImageIcon(userDir.replaceAll("\\\\", "/") + "/icons/executeTestSuite.png"));
        lblExecuteTestSuite.setText("Execute Test Suite");
        lblExecuteTestSuite.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblExecuteTestSuite.setFocusable(false);
        lblExecuteTestSuite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) { lblExecuteTestSuiteMouseEntered(evt); }
            public void mouseExited(java.awt.event.MouseEvent evt) { lblExecuteTestSuiteMouseExited(evt); }
            public void mousePressed(java.awt.event.MouseEvent evt) { lblExecuteTestSuiteMousePressed(evt); }
        });

        javax.swing.GroupLayout pnlExecuteTestSuiteLayout = new javax.swing.GroupLayout(pnlExecuteTestSuite);
        pnlExecuteTestSuite.setLayout(pnlExecuteTestSuiteLayout);
        pnlExecuteTestSuiteLayout.setHorizontalGroup(
            pnlExecuteTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExecuteTestSuite, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        pnlExecuteTestSuiteLayout.setVerticalGroup(
            pnlExecuteTestSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExecuteTestSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuBarGUI.add(pnlExecuteTestSuite);
        pnlMenuBarGUI.add(Box.createVerticalStrut(3));

        pnlAutomationTestReport.setBackground(new java.awt.Color(0, 0, 0));

        lblAutomationTestReport.setFont(new java.awt.Font("Franklin Gothic Book", 0, 16));
        lblAutomationTestReport.setForeground(new java.awt.Color(255, 255, 255));
        lblAutomationTestReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAutomationTestReport.setIcon(new javax.swing.ImageIcon(userDir.replaceAll("\\\\", "/") + "/icons/testRunReport.png"));
        lblAutomationTestReport.setText("Automation Test Report");
        lblAutomationTestReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) { lblAutomationTestReportMouseEntered(evt); }
            public void mouseExited(java.awt.event.MouseEvent evt) { lblAutomationTestReportMouseExited(evt); }
            public void mousePressed(java.awt.event.MouseEvent evt) { lblAutomationTestReportMousePressed(evt); }
        });

        javax.swing.GroupLayout pnlAutomationTestReportLayout = new javax.swing.GroupLayout(pnlAutomationTestReport);
        pnlAutomationTestReport.setLayout(pnlAutomationTestReportLayout);
        pnlAutomationTestReportLayout.setHorizontalGroup(
            pnlAutomationTestReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAutomationTestReport, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        pnlAutomationTestReportLayout.setVerticalGroup(
            pnlAutomationTestReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAutomationTestReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuBarGUI.add(pnlAutomationTestReport);

        menuContainer.add(pnlMenuBarGUI, BorderLayout.WEST);

        // === MAIN LAYOUT ===
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(menuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(969, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>

    // === ALL EVENT HANDLERS (UNCHANGED) ===
    // ... (same as previous version — fully preserved)

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        Image titleIcon = Toolkit.getDefaultToolkit().getImage(constants.userDir + "\\icons\\bolt.jpg");
        this.setIconImage(titleIcon);
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {}

    private void lblAutomationTestReportMouseExited(java.awt.event.MouseEvent evt) {
        pnlAutomationTestReport.setBackground(new Color(0,0,0));
        lblAutomationTestReport.setForeground(new java.awt.Color(255,255,255));
    }

    private void lblAutomationTestReportMouseEntered(java.awt.event.MouseEvent evt) {
        pnlAutomationTestReport.setBackground(new java.awt.Color(250, 128, 114));
        lblAutomationTestReport.setForeground(new java.awt.Color(0,0,0));
    }

    private void lblExecuteTestSuiteMousePressed(java.awt.event.MouseEvent evt) {
        if (lblExecuteTestSuite.getText().contentEquals("Execute Test Suite")) {
            runTestSuite.setLocationRelativeTo(null);
            runTestSuite.setVisible(true);
        } else if (lblExecuteTestSuite.getText().contentEquals("Execute API Test")) {
            runApiTest.setVisible(true);
        }
    }

    private void lblExecuteTestSuiteMouseExited(java.awt.event.MouseEvent evt) {
        pnlExecuteTestSuite.setBackground(new Color(0,0,0));
        lblExecuteTestSuite.setForeground(new java.awt.Color(255,255,255));
    }

    private void lblExecuteTestSuiteMouseEntered(java.awt.event.MouseEvent evt) {
        pnlExecuteTestSuite.setBackground(new java.awt.Color(250, 128, 114));
        lblExecuteTestSuite.setForeground(new java.awt.Color(0,0,0));
    }

    private void pnlEditTestSuiteMouseExited(java.awt.event.MouseEvent evt) {}

    private void pnlEditTestSuiteMouseEntered(java.awt.event.MouseEvent evt) {}

    private void lblEditTestSuiteMousePressed(java.awt.event.MouseEvent evt) {
        if (lblEditTestSuite.getText().contentEquals("Edit Test Suite")) {
            editTestSuite.setLocationRelativeTo(null);
            editTestSuite.setVisible(true);
        } else if (lblEditTestSuite.getText().contentEquals("Edit API Test")) {
            editApiTest.setVisible(true);
        }
    }

    private void lblEditTestSuiteMouseExited(java.awt.event.MouseEvent evt) {
        pnlEditTestSuite.setBackground(new Color(0,0,0));
        lblEditTestSuite.setForeground(new java.awt.Color(255,255,255));
    }

    private void lblEditTestSuiteMouseEntered(java.awt.event.MouseEvent evt) {
        pnlEditTestSuite.setBackground(new java.awt.Color(250, 128, 114));
        lblEditTestSuite.setForeground(new java.awt.Color(0,0,0));
    }

    private void pnlCreateTestSuiteMouseClicked(java.awt.event.MouseEvent evt) {}

    private void lblCreateTestSuiteMousePressed(java.awt.event.MouseEvent evt) {
        if (lblCreateTestSuite.getText().contentEquals("Create Test Suite")) {
            createTestSuite.setLocationRelativeTo(null);
            createTestSuite.setVisible(true);
        } else if (lblCreateTestSuite.getText().contentEquals("Create API Test")) {
            createApiTestSuite.setVisible(true);
        }
    }

    private void lblCreateTestSuiteMouseExited(java.awt.event.MouseEvent evt) {
        pnlCreateTestSuite.setBackground(new Color(0,0,0));
        lblCreateTestSuite.setForeground(new java.awt.Color(255,255,255));
    }

    private void lblCreateTestSuiteMouseEntered(java.awt.event.MouseEvent evt) {
        pnlCreateTestSuite.setBackground(new java.awt.Color(250, 128, 114));
        lblCreateTestSuite.setForeground(new java.awt.Color(0,0,0));
    }

    private void radioBttnGUIMouseEntered(java.awt.event.MouseEvent evt) {
        radioBttnGUI.setForeground(new java.awt.Color(250, 128, 114));
    }

    private void radioBttnGUIMouseExited(java.awt.event.MouseEvent evt) {
        radioBttnGUI.setForeground(new java.awt.Color(255,255,153));
    }

    private void radioBttnAPIMouseEntered(java.awt.event.MouseEvent evt) {
        radioBttnAPI.setForeground(new java.awt.Color(250, 128, 114));
    }

    private void radioBttnAPIMouseExited(java.awt.event.MouseEvent evt) {
        radioBttnAPI.setForeground(new java.awt.Color(255,255,153));
    }

    private void radioBttnGUIActionPerformed(java.awt.event.ActionEvent evt) {
        if (radioBttnGUI.isSelected()) {
            radioBttnAPI.setSelected(false);
            lblSettingsAndConfiguration.setEnabled(false);
        } else {
            radioBttnGUI.setSelected(true);
        }
    }

    private void radioBttnAPIActionPerformed(java.awt.event.ActionEvent evt) {
        if (radioBttnAPI.isEnabled() && radioBttnAPI.isSelected()) {
            radioBttnGUI.setSelected(false);
            lblSettingsAndConfiguration.setEnabled(true);
        } else {
            radioBttnAPI.setSelected(true);
            lblCreateTestSuite.setText("Create API Test");
            lblEditTestSuite.setText("Edit API Test");
            lblExecuteTestSuite.setText("Execute API Test");
            lblAutomationTestReport.setText("API Automation Report");
        }
    }

    private void radioBttnGUIMouseClicked(java.awt.event.MouseEvent evt) {
        lblCreateTestSuite.setText("Create Test Suite");
        lblEditTestSuite.setText("Edit Test Suite");
        lblExecuteTestSuite.setText("Execute Test Suite");
        lblAutomationTestReport.setText("Automation Test Report");
    }

    private void radioBttnGUIMousePressed(java.awt.event.MouseEvent evt) {}

    private void lblSettingsAndConfigurationMousePressed(java.awt.event.MouseEvent evt) {
        if (lblSettingsAndConfiguration.isEnabled() && radioBttnAPI.isSelected()) {
            sslCertConfig.setLocationRelativeTo(null);
            sslCertConfig.setVisible(true);
        }
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {
        if (sslCertConfig.isVisible()) sslCertConfig.dispose();
        if (editTestSuite.isVisible()) editTestSuite.dispose();
        if (runTestSuite.isVisible()) runTestSuite.dispose();
        if (createTestSuite.isVisible()) createTestSuite.dispose();
        if (testReporting.isVisible()) testReporting.dispose();
        if (createApiTestSuite.isVisible()) createApiTestSuite.dispose();
        if (editApiTest.isVisible()) editApiTest.dispose();
        if (runApiTest.isVisible()) runApiTest.dispose();
    }

    private void lblAutomationTestReportMousePressed(java.awt.event.MouseEvent evt) {
        if (lblAutomationTestReport.getText().contentEquals("Automation Test Report")) {
            Image titleIcon = Toolkit.getDefaultToolkit().getImage(constants.userDir + "\\icons\\bolt.jpg");
            testReporting.setIconImage(titleIcon);
            JTreeCellRenderer renderer = new JTreeCellRenderer();
            treeTestReporting.setCellRenderer(renderer);
            testReporting.setLocationRelativeTo(null);
            testReporting.setVisible(true);
        }
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        killProcess("chromedriver.exe");
        killProcess("msedgedriver.exe");
        if (editApiTest.isVisible()) saveTestSuitWhenWindowIsGettingClosed();
        if (createApiTestSuite.isVisible()) saveTestFileWhileClosingTheWindow();
    }

    private void radioBttnGUIMouseReleased(java.awt.event.MouseEvent evt) {}

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(AutomationTestRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new AutomationTestRunner().setVisible(true));
    }

    // Variables declaration
    public static javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel lblAutomationTestReport;
    public static javax.swing.JLabel lblBolt;
    public static javax.swing.JLabel lblChooseTestType;
    public static javax.swing.JLabel lblCreateTestSuite;
    public static javax.swing.JLabel lblEditTestSuite;
    public static javax.swing.JLabel lblExecuteTestSuite;
    public static javax.swing.JLabel lblSettingsAndConfiguration;
    public static javax.swing.JPanel pnlAutomationTestReport;
    public static javax.swing.JPanel pnlBolt;
    public static javax.swing.JPanel pnlCreateTestSuite;
    public static javax.swing.JPanel pnlEditTestSuite;
    public static javax.swing.JPanel pnlExecuteTestSuite;
    public static javax.swing.JPanel pnlMenuBarGUI;
    public static javax.swing.JRadioButton radioBttnAPI;
    public static javax.swing.JRadioButton radioBttnGUI;
    // End of variables declaration
}