/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.automation.bolt.gui;

import com.automation.bolt.constants;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Image;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.RoundRectangle2D;
import java.util.HashMap;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicBoolean;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.LayoutStyle;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import io.github.bonigarcia.wdm.WebDriverManager;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author zakir
 */
public class WebElementInspector extends javax.swing.JFrame {
    public WebElementDetailsExtractor extractor = null;
    public WebDriver driver;
    public boolean inspectMode = false;
    public volatile boolean capturing = false;
    public final AtomicBoolean polling = new AtomicBoolean(true);
    
    /**
     * Creates new form NewJFrame
     */
    public WebElementInspector() {
        extractor = new WebElementDetailsExtractorImpl();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        urlField = new JTextField();
        urlLabel = new JLabel();
        scrollPane = new JScrollPane();
        outputArea = new JTextPane();
        loadButton = new JButton();
        inspectButton = new JButton();
        clearButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Test Suite");
        setBounds(new Rectangle(0, 0, 973, 500));
        setIconImages(null);
        setMinimumSize(new Dimension(851, 328));
        setSize(new Dimension(0, 0));
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        urlField.setBackground(new Color(51, 51, 51));
        urlField.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        urlField.setForeground(new Color(255, 255, 255));
        urlField.setHorizontalAlignment(JTextField.LEFT);
        urlField.setText("https://google.com");
        urlField.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        urlField.setCaretColor(new Color(255, 255, 255));
        urlField.setOpaque(true);
        urlField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                urlFieldActionPerformed(evt);
            }
        });

        urlLabel.setText("URL");

        scrollPane.setBackground(new Color(0, 0, 0));
        scrollPane.setForeground(new Color(255, 255, 255));

        outputArea.setEditable(false);
        outputArea.setBackground(new Color(0, 0, 0));
        outputArea.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        outputArea.setFocusable(false);
        scrollPane.setViewportView(outputArea);

        loadButton.setBackground(new Color(0, 0, 0));
        loadButton.setForeground(new Color(255, 255, 255));
        loadButton.setText("Load URL");
        loadButton.setBorderPainted(false);
        loadButton.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                loadButtonMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                loadButtonMouseExited(evt);
            }
        });
        loadButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        inspectButton.setBackground(new Color(0, 0, 0));
        inspectButton.setForeground(new Color(255, 255, 255));
        inspectButton.setText("Inspect");
        inspectButton.setBorderPainted(false);
        inspectButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                inspectButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new Color(0, 0, 0));
        clearButton.setForeground(new Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.setBorderPainted(false);
        clearButton.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                clearButtonMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                clearButtonMouseExited(evt);
            }
        });
        clearButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(scrollPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(urlLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(urlField, GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inspectButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(urlLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(urlField, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                            .addComponent(loadButton)
                            .addComponent(inspectButton)
                            .addComponent(clearButton))))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        getAccessibleContext().setAccessibleParent(this);

        setSize(new Dimension(865, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(ActionEvent evt) {//GEN-First:event_loadButtonActionPerformed
        System.out.println("Load URL button clicked: " + urlField.getText());
        
        // Disable all buttons immediately on the EDT
        SwingUtilities.invokeLater(() -> {
            loadButton.setText("Loading URL");
            loadButton.setEnabled(false);
            inspectButton.setEnabled(false);
            clearButton.setEnabled(false);
        });

        // Check if driver exists and is usable
        if (driver == null || !isBrowserOpen()) {
            CompletableFuture.runAsync(() -> {
                try {
                    WebDriverManager.chromedriver().setup();
                    ChromeOptions co = new ChromeOptions();
                    co.addArguments("--remote-allow-origins=*");
                    co.addArguments("--start-maximized");
                    co.addArguments("--ignore-certificate-errors");
                    co.addArguments("--blink-settings=imagesEnabled=true");
                    co.addArguments("--lang=en-US"); // Ensure UTF-8 support
                    HashMap<String, Object> prefs = new HashMap<>();
                    prefs.put("profile.default_content_setting_values.notifications", 2);
                    co.setExperimentalOption("prefs", prefs);
                    driver = new ChromeDriver(co);
                    System.out.println("WebDriver initialized successfully");
                    // Load URL after successful initialization
                    loadUrl(urlField.getText());
                } catch (Exception ex) {
                    SwingUtilities.invokeLater(() -> {
                        appendToOutputArea("Error initializing WebDriver: " + ex.getMessage() + "\n");
                        loadButton.setText("Load URL");
                        loadButton.setEnabled(true);
                        inspectButton.setEnabled(true);
                        clearButton.setEnabled(true);
                    });
                    System.out.println("Error initializing WebDriver: " + ex.getMessage());
                    ex.printStackTrace();
                }
            });
        } else {
            // Load URL directly if driver is already initialized
            loadUrl(urlField.getText());
        }
    }                                          

    private void inspectButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_inspectButtonActionPerformed
        System.out.println("Toggle Inspect button clicked");
        inspectMode = !inspectMode;
        inspectButton.setBackground(inspectMode ? new Color(34, 139, 34) : new Color(0, 0, 0));
        inspectButton.setForeground(new Color(255, 255, 255)); // Ensure foreground is white when not hovered
        appendToOutputArea((inspectMode ? "Inspect Mode: Click an element in the browser (ensure browser window is focused)" : "\nInspect Mode: Disabled") + "\n");
        System.out.println("Inspect Mode Toggled: " + inspectMode);
        toggleInspectMode(inspectMode);
    }//GEN-LAST:event_inspectButtonActionPerformed

    private void clearButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        System.out.println("Clear button clicked");
        SwingUtilities.invokeLater(() -> {
            try {
                outputArea.setText(""); // Clear the outputArea
                StyledDocument doc = outputArea.getStyledDocument();
                SimpleAttributeSet attrs = new SimpleAttributeSet();
                String devanagariFont = getAvailableDevanagariFont();
                StyleConstants.setFontFamily(attrs, devanagariFont);
                StyleConstants.setFontSize(attrs, 14);
                StyleConstants.setForeground(attrs, new Color(255, 255, 255));
                StyleConstants.setBackground(attrs, new Color(0, 0, 0));
                doc.setCharacterAttributes(0, doc.getLength(), attrs, true);
                System.out.println("Output area cleared");
            } catch (Exception e) {
                System.out.println("Error clearing outputArea: " + e.getMessage());
                appendToOutputArea("Error clearing outputArea: " + e.getMessage() + "\n");
            }
        });
    }//GEN-LAST:event_clearButtonActionPerformed

    private void urlFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_urlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlFieldActionPerformed

    private void loadButtonMouseEntered(MouseEvent evt) {//GEN-FIRST:event_loadButtonMouseEntered
        loadButton.setBackground(new java.awt.Color(250, 128, 114));
        loadButton.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_loadButtonMouseEntered

    private void loadButtonMouseExited(MouseEvent evt) {//GEN-FIRST:event_loadButtonMouseExited
        loadButton.setBackground(new java.awt.Color(0,0,0));
        loadButton.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_loadButtonMouseExited

    private void clearButtonMouseEntered(MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseEntered
        clearButton.setBackground(new java.awt.Color(250, 128, 114));
        clearButton.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_clearButtonMouseEntered

    private void clearButtonMouseExited(MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseExited
       clearButton.setBackground(new java.awt.Color(0,0,0));
       clearButton.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_clearButtonMouseExited

    private void inspectButtonMouseEntered(MouseEvent evt) {//GEN-FIRST:event_inspectButtonMouseEntered
        inspectButton.setBackground(new java.awt.Color(250, 128, 114));
        inspectButton.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_inspectButtonMouseEntered

    private void inspectButtonMouseExited(MouseEvent evt) {//GEN-FIRST:event_inspectButtonMouseExited
        inspectButton.setBackground(inspectMode ? new java.awt.Color(34, 139, 34) : new java.awt.Color(0, 0, 0));
        inspectButton.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_inspectButtonMouseExited

    private void formWindowOpened(WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Image titleIcon = Toolkit.getDefaultToolkit().getImage(constants.userDir+"/icons/bolt.jpg");
        this.setIconImage(titleIcon);
    }//GEN-LAST:event_formWindowOpened
    
    private void loadUrl(String url) {
        CompletableFuture.runAsync(() -> {
            try {
                driver.get(url);
                Thread.sleep(2000);
                SwingUtilities.invokeLater(() -> {
                    // Set outputArea and scrollPane background to black and text color to white
                    outputArea.setOpaque(true);
                    outputArea.setBackground(new Color(0, 0, 0));
                    outputArea.setForeground(new Color(255, 255, 255));
                    scrollPane.setBackground(new Color(0, 0, 0));
                    scrollPane.setForeground(new Color(255, 255, 255));
                    scrollPane.getViewport().setBackground(new Color(0, 0, 0));
                    StyledDocument doc = outputArea.getStyledDocument();
                    SimpleAttributeSet attrs = new SimpleAttributeSet();
                    String devanagariFont = getAvailableDevanagariFont();
                    StyleConstants.setFontFamily(attrs, devanagariFont);
                    StyleConstants.setFontSize(attrs, 14);
                    StyleConstants.setForeground(attrs, new Color(255, 255, 255));
                    StyleConstants.setBackground(attrs, new Color(0, 0, 0));
                    doc.setCharacterAttributes(0, doc.getLength(), attrs, true);
                    
                    appendToOutputArea("Loaded URL: " + url + "\n");
                    loadButton.setText("Load URL");
                    loadButton.setEnabled(true);
                    inspectButton.setEnabled(true);
                    clearButton.setEnabled(true);
                });
                System.out.println("Loaded URL: " + url);
                if (inspectMode) {
                    inspectMode = false;
                    inspectButton.setBackground(new Color(0, 0, 0));
                    inspectButton.setForeground(new Color(255, 255, 255));
                    SwingUtilities.invokeLater(() -> {
                        appendToOutputArea("\nInspect Mode: Disabled\n");
                        loadButton.setText("Load URL");
                        loadButton.setEnabled(true);
                        inspectButton.setEnabled(true);
                        clearButton.setEnabled(true);
                    });
                    toggleInspectMode(false);
                }
            } catch (Exception ex) {
                SwingUtilities.invokeLater(() -> {
                    appendToOutputArea("Error loading URL: " + ex.getMessage() + "\n");
                    loadButton.setText("Load URL");
                    loadButton.setEnabled(true);
                    inspectButton.setEnabled(true);
                    clearButton.setEnabled(true);
                });
                System.out.println("Error loading URL: " + ex.getMessage());
                ex.printStackTrace();
            }
        });
    }
    
    private void appendToOutputArea(String text) {
        SwingUtilities.invokeLater(() -> {
            try {
                StyledDocument doc = outputArea.getStyledDocument();
                SimpleAttributeSet attrs = new SimpleAttributeSet();
                String devanagariFont = getAvailableDevanagariFont();
                StyleConstants.setFontFamily(attrs, devanagariFont);
                StyleConstants.setFontSize(attrs, 14);
                StyleConstants.setForeground(attrs, new Color(255, 255, 255));
                StyleConstants.setBackground(attrs, new Color(0, 0, 0));
                System.out.println("Appending text: " + text); // Debug the raw text
                doc.insertString(doc.getLength(), text, attrs);
                outputArea.setCaretPosition(doc.getLength());
            } catch (BadLocationException e) {
                System.out.println("Error appending to outputArea: " + e.getMessage());
            }
        });
    }
    
    private void toggleInspectMode(boolean enable) {
        System.out.println("Toggling Inspect Mode: " + enable);
        capturing = enable;
        if (!enable) {
            try {
                JavascriptExecutor js = (JavascriptExecutor) driver;
                js.executeScript(
                    "if (window.elementCapture) {" +
                    "  document.removeEventListener('click', window.elementCapture, { capture: true });" +
                    "  document.removeEventListener('mouseover', window.elementHover, { capture: true });" +
                    "  document.removeEventListener('mouseout', window.elementHoverOut, { capture: true });" +
                    "  window.elementCapture = null;" +
                    "  window.elementHover = null;" +
                    "  window.elementHoverOut = null;" +
                    "  window.elementDetails = null;" +
                    "  document.body.style.removeProperty('pointer-events');" +
                    "  console.log('Inspect mode disabled, all listeners and styles removed');" +
                    "}"
                );
                System.out.println("JavaScript listeners cleared and normal interaction restored");
            } catch (Exception ex) {
                System.out.println("Error clearing JavaScript listeners: " + ex.getMessage());
                ex.printStackTrace();
                appendToOutputArea("Error clearing listeners: " + ex.getMessage() + "\n");
            }
            return;
        }

        CompletableFuture.runAsync(() -> {
            try {
                JavascriptExecutor js = (JavascriptExecutor) driver;
                driver.switchTo().defaultContent();
                Object initResult = js.executeScript(
                    "try {" +
                    "  console.log('Initializing listeners...');" +
                    "  window.elementDetails = null;" +
                    "  window.escapeText = function(text) {" +
                    "    try {" +
                    "      if (!text) return '';" +
                    "      return text.replace(/'/g, \"\\\\'\").replace(/\\\"/g, \"\\\\\\\"\");" +
                    "    } catch (err) {" +
                    "      console.error('escapeText error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.hasSpacesOrNewlines = function(value) {" +
                    "    try {" +
                    "      if (!value) return false;" +
                    "      return /^\\s|\\s$|[\\n\\r]/.test(value);" +
                    "    } catch (err) {" +
                    "      console.error('hasSpacesOrNewlines error: ' + err.message);" +
                    "      return false;" +
                    "    }" +
                    "  };" +
                    "  window.normalizeText = function(text) {" +
                    "    try {" +
                    "      if (!text) return '';" +
                    "      return text.replace(/[\\n\\r]+/g, ' ').replace(/\\s+/g, ' ');" +
                    "    } catch (err) {" +
                    "      console.error('normalizeText error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.getCssSelector = function(element) {" +
                    "    try {" +
                    "      if (!element || !element.tagName) return '';" +
                    "      var path = [];" +
                    "      var current = element;" +
                    "      while (current && current.nodeType === 1) {" +
                    "        var selector = current.tagName.toLowerCase();" +
                    "        var siblings = current.parentNode ? Array.from(current.parentNode.children).filter(function(child) {" +
                    "          return child.tagName === current.tagName;" +
                    "        }) : [];" +
                    "        if (siblings.length > 1) {" +
                    "          var index = siblings.indexOf(current) + 1;" +
                    "          selector += ':nth-of-type(' + index + ')';" +
                    "        }" +
                    "        path.unshift(selector);" +
                    "        current = current.parentNode;" +
                    "        if (path.length > 3) break;" +
                    "      }" +
                    "      return path.join(' > ') || element.tagName.toLowerCase();" +
                    "    } catch (err) {" +
                    "      console.error('getCssSelector error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.getAbsoluteXPath = function(element) {" +
                    "    try {" +
                    "      if (!element || !element.tagName) return '';" +
                    "      var paths = [];" +
                    "      var current = element;" +
                    "      while (current && current.nodeType === 1 && current !== document.documentElement) {" +
                    "        var index = 0;" +
                    "        var siblings = current.parentNode ? Array.from(current.parentNode.childNodes).filter(function(node) {" +
                    "          return node.nodeType === 1 && node.tagName === current.tagName;" +
                    "        }) : [];" +
                    "        for (var i = 0; i < siblings.length; i++) {" +
                    "          if (siblings[i] === current) {" +
                    "            index = i + 1;" +
                    "            break;" +
                    "          }" +
                    "        }" +
                    "        var tag = current.tagName.toLowerCase();" +
                    "        var segment = index > 0 ? tag + '[' + index + ']' : tag;" +
                    "        paths.unshift(segment);" +
                    "        current = current.parentNode;" +
                    "      }" +
                    "      return paths.length ? '/html' + (paths.length ? '/' + paths.join('/') : '') : '';" +
                    "    } catch (err) {" +
                    "      console.error('getAbsoluteXPath error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.getRelativeXPath = function(element) {" +
                    "    try {" +
                    "      if (!element || !element.tagName) return '';" +
                    "      var tag = element.tagName.toLowerCase();" +
                    "      var predicates = [];" +
                    "      if (element.id && element.id.trim()) {" +
                    "        var idValue = element.id;" +
                    "        var escapedId = window.escapeText(idValue);" +
                    "        predicates.push('@id=\\'' + escapedId + '\\'');" +
                    "      }" +
                    "      if (element.className && element.className.trim()) {" +
                    "        var classValue = element.className;" +
                    "        var escapedClass = window.escapeText(classValue);" +
                    "        predicates.push('@class=\\'' + escapedClass + '\\'');" +
                    "      }" +
                    "      var text = element.textContent ? window.normalizeText(element.textContent) : '';" +
                    "      if (text && text.trim().length > 0) {" +
                    "        var escapedText = window.escapeText(text.trim());" +
                    "        predicates.push('contains(normalize-space(text()),\\'' + escapedText + '\\')');" +
                    "      }" +
                    "      var xpath = '//' + tag;" +
                    "      if (predicates.length > 0) {" +
                    "        xpath += '[' + predicates.join(' and ') + ']';" +
                    "      }" +
                    "      return xpath;" +
                    "    } catch (err) {" +
                    "      console.error('getRelativeXPath error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.elementCapture = function(e) {" +
                    "    try {" +
                    "      e.preventDefault();" +
                    "      e.stopPropagation();" +
                    "      var el = e.target;" +
                    "      var normalizedText = el.textContent ? window.normalizeText(el.textContent.substring(0, 50)) : '';" +
                    "      var details = {" +
                    "        tagName: el.tagName ? el.tagName.toLowerCase() : ''," +
                    "        text: normalizedText," +
                    "        id: el.id || ''," +
                    "        class: el.className || ''," +
                    "        cssSelector: window.getCssSelector(el)," +
                    "        absoluteXPath: window.getAbsoluteXPath(el)," +
                    "        relativeXPath: window.getRelativeXPath(el)" +
                    "      };" +
                    "      window.elementDetails = details;" +
                    "      return JSON.stringify(details);" +
                    "    } catch (err) {" +
                    "      console.error('elementCapture error: ' + err.message);" +
                    "      return 'Error: ' + err.message;" +
                    "    }" +
                    "  };" +
                    "  window.elementHover = function(e) {" +
                    "    try {" +
                    "      e.target.style.outline = '2px solid red';" +
                    "    } catch (err) {" +
                    "      console.error('elementHover error: ' + err.message);" +
                    "    }" +
                    "  };" +
                    "  window.elementHoverOut = function(e) {" +
                    "    try {" +
                    "      e.target.style.outline = '';" +
                    "    } catch (err) {" +
                    "      console.error('elementHoverOut error: ' + err.message);" +
                    "    }" +
                    "  };" +
                    "  window.checkListeners = function() {" +
                    "    try {" +
                    "      return !!window.elementCapture;" +
                    "    } catch (err) {" +
                    "      console.error('checkListeners error: ' + err.message);" +
                    "      return false;" +
                    "    }" +
                    "  };" +
                    "  document.removeEventListener('click', window.elementCapture);" +
                    "  document.removeEventListener('mouseover', window.elementHover);" +
                    "  document.removeEventListener('mouseout', window.elementHoverOut);" +
                    "  document.addEventListener('click', window.elementCapture, { capture: true, passive: false });" +
                    "  document.addEventListener('mouseover', window.elementHover, { capture: true, passive: true });" +
                    "  document.addEventListener('mouseout', window.elementHoverOut, { capture: true, passive: true });" +
                    "  setTimeout(function() {" +
                    "    window.checkListeners();" +
                    "  }, 500);" +
                    "  console.log('Listeners setup complete');" +
                    "  return { status: 'Listeners setup initiated' };" +
                    "} catch (err) {" +
                    "  console.error('Initialization error: ' + err.message);" +
                    "  return { status: 'Error: ' + err.message };" +
                    "}"
                );
                System.out.println("initResult: " + (initResult != null ? initResult.toString() : "null"));
                if (initResult == null || initResult.toString().contains("Error:")) {
                    String errorMsg = initResult != null ? initResult.toString() : "Initialization result is null";
                    appendToOutputArea("Failed to initialize listeners: " + errorMsg + "\n");
                    return;
                }

                if (initResult instanceof HashMap) {
                    HashMap<String, Object> resultMap = (HashMap<String, Object>) initResult;
                    String status = (String) resultMap.get("status");
                    System.out.println("Initialization status: " + status);
                    if (!"Listeners setup initiated".equals(status)) {
                        appendToOutputArea("Failed to initialize listeners: " + status + "\n");
                        return;
                    }
                }

                Thread.sleep(1000);
                Object listenerStatus = js.executeScript("return window.checkListeners ? window.checkListeners() : false;");
                System.out.println("Listener status after setup: " + listenerStatus);
                if (listenerStatus instanceof Boolean && !(Boolean) listenerStatus) {
                    appendToOutputArea("Error: Listeners not attached properly\n");
                    return;
                }

                while (capturing && driver != null) {
                    try {
                        Object result = js.executeScript(
                            "try {" +
                            "  console.log('Polling elementDetails...');" +
                            "  var result = window.elementDetails;" +
                            "  if (result) {" +
                            "    window.elementDetails = null;" +
                            "    return { details: JSON.stringify(result) };" +
                            "  }" +
                            "  return { details: null };" +
                            "} catch (err) {" +
                            "  console.error('Poll error: ' + err.message);" +
                            "  return { details: 'Error: ' + err.message };" +
                            "}"
                        );
                        String details = null;
                        if (result instanceof HashMap) {
                            HashMap<String, Object> resultMap = (HashMap<String, Object>) result;
                            details = (String) resultMap.get("details");
                        }
                        final String finalDetails = details;
                        if (finalDetails != null && !finalDetails.isEmpty() && !finalDetails.startsWith("Error:") && !finalDetails.equals("null")) {
                            String parsedDetails = extractor.extractElementDetails(finalDetails);
                            System.out.println("Raw parsed details: " + (parsedDetails != null ? parsedDetails : "null")); // Debug raw text
                            if (parsedDetails != null && !parsedDetails.trim().isEmpty() && !parsedDetails.contains("No valid element details parsed")) {
                                String elementId = "Element_" + System.currentTimeMillis();
                                extractor.storeInRepository(elementId, parsedDetails);
                                appendElementDetails(elementId, parsedDetails);
                            } else {
                                System.out.println("No valid details parsed: " + parsedDetails);
                                appendToOutputArea("Element Details: No valid element details parsed: " + parsedDetails + "\n");
                            }
                        } else if (finalDetails != null && finalDetails.startsWith("Error:")) {
                            System.out.println("JavaScript error: " + finalDetails);
                            appendToOutputArea("JavaScript error: " + finalDetails + "\n");
                        }
                        Thread.sleep(500);
                    } catch (Exception ex) {
                        System.out.println("Capture error: " + ex.getMessage());
                        ex.printStackTrace();
                        appendToOutputArea("Capture error: " + ex.getMessage() + "\n");
                    }
                }
            } catch (Exception ex) {
                System.out.println("Error initializing listeners: " + ex.getMessage());
                ex.printStackTrace();
                appendToOutputArea("Error initializing listeners: " + ex.getMessage() + "\n");
            }
        });
    }
    
    private String getAvailableDevanagariFont() {
        String[] devanagariFonts = {"Mangal", "Noto Sans Devanagari", "Arial Unicode MS"};
        for (String font : devanagariFonts) {
            if (Font.getFont(font) != null) {
                System.out.println("Using font: " + font);
                return font;
            }
        }
        System.out.println("Warning: No Devanagari font found, falling back to default");
        return "Dialog"; // Fallback to system default
    }
    
    private void appendElementDetails(String elementId, String parsedDetails) {
        SwingUtilities.invokeLater(() -> {
            try {
                StyledDocument doc = outputArea.getStyledDocument();
                SimpleAttributeSet attrs = new SimpleAttributeSet();
                String devanagariFont = getAvailableDevanagariFont();
                StyleConstants.setFontFamily(attrs, devanagariFont);
                StyleConstants.setFontSize(attrs, 14);
                StyleConstants.setForeground(attrs, new Color(255, 255, 255));
                StyleConstants.setBackground(attrs, new Color(0, 0, 0));

                doc.insertString(doc.getLength(), "\n----\nStored in repository as: " + elementId + "\nElement Details:\n", attrs);

                String[] lines = parsedDetails.split("\n");
                String relativeXPath = "";
                String absoluteXPath = "";
                for (String line : lines) {
                    if (line.startsWith("relativeXPath:")) {
                        relativeXPath = line.substring("relativeXPath:".length()).trim();
                        CustomButton copyButton = new CustomButton("Copy", 8, 1, new Color(250, 128, 114), new Color(250, 128, 114));
                        copyButton.setFont(new Font("Arial", Font.PLAIN, 10));
                        copyButton.setMargin(new Insets(2, 4, 2, 4));
                        copyButton.setForeground(Color.WHITE);
                        String finalXPath = relativeXPath;
                        copyButton.addActionListener(e -> {
                            StringSelection selection = new StringSelection(finalXPath);
                            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                            clipboard.setContents(selection, null);
                            appendToOutputArea("Copied to clipboard: " + finalXPath + "\n");
                        });
                        CustomButton addButton = new CustomButton("Add", 8, 1, new Color(250, 128, 114), new Color(250, 128, 114));
                        addButton.setFont(new Font("Arial", Font.PLAIN, 10));
                        addButton.setMargin(new Insets(2, 4, 2, 4));
                        addButton.setForeground(Color.WHITE);
                        addButton.addActionListener(e -> {
                            appendToOutputArea("Element added to the repository\n");
                            CreateTestSuite.addWebElementToRepository(elementId,finalXPath);
                        });
                        Style buttonStyle = doc.addStyle("button" + System.currentTimeMillis(), null);
                        StyleConstants.setComponent(buttonStyle, copyButton);
                        doc.insertString(doc.getLength(), " ", buttonStyle);
                        doc.insertString(doc.getLength(), " ", attrs);
                        Style addButtonStyle = doc.addStyle("addButton" + System.currentTimeMillis(), null);
                        StyleConstants.setComponent(addButtonStyle, addButton);
                        doc.insertString(doc.getLength(), " ", addButtonStyle);
                        doc.insertString(doc.getLength(), " relativeXPath: " + relativeXPath + "\n", attrs);
                    } else if (line.startsWith("absoluteXPath:")) {
                        absoluteXPath = line.substring("absoluteXPath:".length()).trim();
                        CustomButton copyButton = new CustomButton("Copy", 8, 1, new Color(250, 128, 114), new Color(250, 128, 114));
                        copyButton.setFont(new Font("Arial", Font.PLAIN, 10));
                        copyButton.setMargin(new Insets(2, 4, 2, 4));
                        copyButton.setForeground(Color.WHITE);
                        String finalXPath = absoluteXPath;
                        copyButton.addActionListener(e -> {
                            StringSelection selection = new StringSelection(finalXPath);
                            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                            clipboard.setContents(selection, null);
                            appendToOutputArea("Copied to clipboard: " + finalXPath + "\n");
                        });
                        CustomButton addButton = new CustomButton("Add", 8, 1, new Color(250, 128, 114), new Color(250, 128, 114));
                        addButton.setFont(new Font("Arial", Font.PLAIN, 10));
                        addButton.setMargin(new Insets(2, 4, 2, 4));
                        addButton.setForeground(Color.WHITE);
                        addButton.addActionListener(e -> {
                            appendToOutputArea("Element added to the repository\n");
                        });
                        Style buttonStyle = doc.addStyle("button" + System.currentTimeMillis(), null);
                        StyleConstants.setComponent(buttonStyle, copyButton);
                        doc.insertString(doc.getLength(), " ", buttonStyle);
                        doc.insertString(doc.getLength(), " ", attrs);
                        Style addButtonStyle = doc.addStyle("addButton" + System.currentTimeMillis(), null);
                        StyleConstants.setComponent(addButtonStyle, addButton);
                        doc.insertString(doc.getLength(), " ", addButtonStyle);
                        doc.insertString(doc.getLength(), " absoluteXPath: " + absoluteXPath + "\n", attrs);
                    } else {
                        doc.insertString(doc.getLength(), line + "\n", attrs);
                    }
                }
                outputArea.setCaretPosition(doc.getLength());
            } catch (BadLocationException e) {
                System.out.println("Error appending element details: " + e.getMessage());
            }
        });
    }

    public static class CustomButton extends JButton {
        protected Color defaultColor = Color.BLACK;
        protected Color hoverColor = new Color(250, 128, 114);
        protected Color disabledColor = new Color(50, 50, 50);
        protected Color borderColor = null;
        protected Color borderHoverColor = null;
        protected boolean isHovered = false;
        protected boolean isDisabled = false;
        private int arc = 8;
        private int shadowOffset = 1;
        
        public CustomButton(String text) {
            this(text, 12, 1, null, null);
        }

        public CustomButton(String text, int arc, int shadowOffset) {
            this(text, arc, shadowOffset, null, null);
        }

        public CustomButton(String text, int arc, int shadowOffset, Color borderColor, Color borderHoverColor) {
            super(text);
            this.arc = arc;
            this.shadowOffset = shadowOffset;
            this.borderColor = borderColor;
            this.borderHoverColor = borderHoverColor;
            setOpaque(false);
            setContentAreaFilled(false);
            setBorderPainted(false);
            setFocusPainted(false);
            setForeground(Color.WHITE);
            setFont(new Font("Arial", Font.BOLD, 12));
            setMargin(new Insets(4, 10, 4, 10));
            setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor to pointer
            addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    isHovered = true;
                    repaint();
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    isHovered = false;
                    repaint();
                }
            });
        }

        public void setDisabled(boolean disabled) {
            this.isDisabled = disabled;
            repaint();
        }

        public void setBackgroundColor(Color color) {
            this.defaultColor = color;
            repaint();
        }

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(new Color(0, 0, 0, 50));
            g2.fill(new RoundRectangle2D.Float(shadowOffset, shadowOffset, getWidth() - shadowOffset, getHeight() - shadowOffset, arc, arc));
            if (isDisabled || !isEnabled()) {
                g2.setColor(isHovered ? disabledColor.brighter() : disabledColor);
            } else {
                g2.setColor(isHovered ? hoverColor : defaultColor);
            }
            g2.fill(new RoundRectangle2D.Float(0, 0, getWidth() - shadowOffset, getHeight() - shadowOffset, arc, arc));
            if (borderColor != null) {
                g2.setColor(isHovered && borderHoverColor != null ? borderHoverColor : borderColor);
                g2.setStroke(new BasicStroke(1.5f));
                g2.draw(new RoundRectangle2D.Float(0, 0, getWidth() - shadowOffset, getHeight() - shadowOffset, arc, arc));
            }
            super.paintComponent(g);
            g2.dispose();
        }
    }
    
    private boolean isBrowserOpen() {
        if (driver == null) {
            return false;
        }
        try {
            driver.getWindowHandle();
            return true;
        } catch (Exception e) {
            System.out.println("Browser window is closed or unavailable: " + e.getMessage());
            return false;
        }
    }
    
    private void startBrowserPolling() {
        CompletableFuture.runAsync(() -> {
            while (polling.get() && driver != null) {
                try {
                    if (!isBrowserOpen()) {
                        System.out.println("Browser window closed, closing JFrame");
                        SwingUtilities.invokeLater(() -> {
                            appendToOutputArea("Browser window closed, shutting down application\n");
                            if (inspectMode) {
                                toggleInspectMode(false);
                            }
                            this.dispose();
                            polling.set(false);
                        });
                        break;
                    }
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    System.out.println("Browser polling interrupted: " + e.getMessage());
                    break;
                }
            }
        });
    }

    @Override
    public void dispose() {
        polling.set(false); // Stop the polling thread
        if (driver != null) {
            try {
                driver.quit(); // Close the WebDriver
                System.out.println("WebDriver closed successfully");
                appendToOutputArea("WebDriver closed\n");
            } catch (Exception e) {
                System.out.println("Error closing WebDriver: " + e.getMessage());
                appendToOutputArea("Error closing WebDriver: " + e.getMessage() + "\n");
            }
            driver = null; // Nullify the driver reference
        }
        super.dispose(); // Call the parent dispose method
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WebElementInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WebElementInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WebElementInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WebElementInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //System.setProperty("java.awt.headless", "false");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WebElementInspector().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton clearButton;
    public JButton inspectButton;
    public JButton loadButton;
    public JTextPane outputArea;
    public JScrollPane scrollPane;
    public JTextField urlField;
    public JLabel urlLabel;
    // End of variables declaration//GEN-END:variables

    private void contentEquals(String testId) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}