/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.automation.bolt.gui;

import com.automation.bolt.constants;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Image;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.RoundRectangle2D;
import java.util.HashMap;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicBoolean;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.JSeparator;
import javax.swing.LayoutStyle;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import javax.swing.plaf.basic.BasicTextPaneUI;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import io.github.bonigarcia.wdm.WebDriverManager;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import org.json.JSONObject;

/**
 *
 * @author zakir
 */
public class WebElementInspector extends javax.swing.JFrame {
    public WebElementDetailsExtractor extractor = null;
    public WebDriver driver;
    public boolean inspectMode = false;
    public volatile boolean capturing = false;
    public final AtomicBoolean polling = new AtomicBoolean(true);
    
    /**
     * Creates new form NewJFrame
     */
    public WebElementInspector() {
        extractor = new WebElementDetailsExtractorImpl();
        initComponents();
        outputArea.setOpaque(true);
        outputArea.setBackground(new java.awt.Color(0, 0, 0));
        outputArea.setForeground(new java.awt.Color(255, 255, 255));
        outputArea.setCaretColor(new java.awt.Color(255, 255, 255));
        outputArea.setUI(new BasicTextPaneUI()); // Use basic UI to avoid Nimbus overrides
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        urlField = new JTextField();
        urlLabel = new JLabel();
        scrollPane = new JScrollPane();
        outputArea = new JTextPane();
        loadButton = new JButton();
        inspectButton = new JButton();
        clearButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Web Element Inspector");
        setBackground(new Color(0, 0, 0));
        setBounds(new Rectangle(0, 0, 973, 500));
        setIconImages(null);
        setMinimumSize(new Dimension(851, 328));
        setSize(new Dimension(0, 0));
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        urlField.setBackground(new Color(0, 0, 0));
        urlField.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        urlField.setForeground(new Color(255, 255, 255));
        urlField.setHorizontalAlignment(JTextField.LEFT);
        urlField.setText("https://google.com");
        urlField.setBorder(BorderFactory.createLineBorder(new Color(255, 255, 255)));
        urlField.setCaretColor(new Color(255, 255, 255));
        urlField.setOpaque(true);
        urlField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                urlFieldActionPerformed(evt);
            }
        });

        urlLabel.setText("URL");

        scrollPane.setBackground(new Color(0, 0, 0));
        scrollPane.setForeground(new Color(255, 255, 255));

        outputArea.setEditable(false);
        outputArea.setBackground(new Color(0, 0, 0));
        outputArea.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        outputArea.setForeground(new Color(255, 153, 153));
        outputArea.setFocusable(false);
        scrollPane.setViewportView(outputArea);

        loadButton.setBackground(new Color(0, 0, 0));
        loadButton.setForeground(new Color(255, 255, 255));
        loadButton.setText("Load URL");
        loadButton.setBorderPainted(false);
        loadButton.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                loadButtonMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                loadButtonMouseExited(evt);
            }
        });
        loadButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        inspectButton.setBackground(new Color(0, 0, 0));
        inspectButton.setForeground(new Color(255, 255, 255));
        inspectButton.setText("Inspect");
        inspectButton.setBorderPainted(false);
        inspectButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                inspectButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new Color(0, 0, 0));
        clearButton.setForeground(new Color(255, 255, 255));
        clearButton.setText("Clear");
        clearButton.setBorderPainted(false);
        clearButton.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                clearButtonMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                clearButtonMouseExited(evt);
            }
        });
        clearButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(scrollPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(urlLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(urlField, GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inspectButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(urlLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(urlField, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                .addComponent(loadButton)
                                .addComponent(inspectButton)
                                .addComponent(clearButton))))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addGap(1, 1, 1))
            );

        getAccessibleContext().setAccessibleParent(this);

        setSize(new Dimension(646, 485));
        setLocationRelativeTo(null);
    }                     

    private void loadButtonActionPerformed(ActionEvent evt) {                                           
        System.out.println("Load URL button clicked: " + urlField.getText());
        
        // Disable all buttons immediately on the EDT
        SwingUtilities.invokeLater(() -> {
            loadButton.setText("Loading URL");
            loadButton.setEnabled(false);
            inspectButton.setEnabled(false);
            clearButton.setEnabled(false);
        });

        // Check if driver exists and is usable
        if (driver == null || !isBrowserOpen()) {
            CompletableFuture.runAsync(() -> {
                try {
                    WebDriverManager.chromedriver().setup();
                    ChromeOptions co = new ChromeOptions();
                    co.addArguments("--remote-allow-origins=*");
                    co.addArguments("--start-maximized");
                    co.addArguments("--ignore-certificate-errors");
                    co.addArguments("--blink-settings=imagesEnabled=true");
                    co.addArguments("--lang=en-US"); // Ensure UTF-8 support
                    HashMap<String, Object> prefs = new HashMap<>();
                    prefs.put("profile.default_content_setting_values.notifications", 2);
                    co.setExperimentalOption("prefs", prefs);
                    driver = new ChromeDriver(co);
                    System.out.println("WebDriver initialized successfully");
                    // Load URL after successful initialization
                    loadUrl(urlField.getText());
                } catch (Exception ex) {
                    SwingUtilities.invokeLater(() -> {
                        appendToOutputArea("Error initializing WebDriver: " + ex.getMessage() + "\n");
                        loadButton.setText("Load URL");
                        loadButton.setEnabled(true);
                        inspectButton.setEnabled(true);
                        clearButton.setEnabled(true);
                    });
                    System.out.println("Error initializing WebDriver: " + ex.getMessage());
                    ex.printStackTrace();
                }
            });
        } else {
            // Load URL directly if driver is already initialized
            loadUrl(urlField.getText());
        }
    }                                          

    private void inspectButtonActionPerformed(ActionEvent evt) {
        System.out.println("Toggle Inspect button clicked");
        inspectMode = !inspectMode;
        inspectButton.setBackground(inspectMode ? new Color(34, 139, 34) : new Color(0, 0, 0));
        inspectButton.setForeground(new Color(255, 255, 255)); // Ensure foreground is white when not hovered
        appendToOutputArea((inspectMode ? "Inspect Mode: Click an element in the browser (ensure browser window is focused)" : "\nInspect Mode: Disabled") + "\n");
        System.out.println("Inspect Mode Toggled: " + inspectMode);
        toggleInspectMode(inspectMode);
    }                                             

    private void clearButtonActionPerformed(ActionEvent evt) {
        System.out.println("Clear button clicked");
        SwingUtilities.invokeLater(() -> {
            try {
                outputArea.setText(""); // Clear the outputArea
                StyledDocument doc = outputArea.getStyledDocument();
                SimpleAttributeSet attrs = new SimpleAttributeSet();
                String devanagariFont = getAvailableDevanagariFont();
                StyleConstants.setFontFamily(attrs, devanagariFont);
                StyleConstants.setFontSize(attrs, 14);
                doc.setCharacterAttributes(0, doc.getLength(), attrs, true);
                outputArea.setBackground(new Color(0, 0, 0)); // Reinforce black background
                outputArea.setForeground(new Color(255, 255, 255)); // Reinforce white foreground
                System.out.println("Output area cleared");
            } catch (Exception e) {
                System.out.println("Error clearing outputArea: " + e.getMessage());
                appendToOutputArea("Error clearing outputArea: " + e.getMessage() + "\n");
            }
        });
    }                                           

    private void urlFieldActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }                                        

    private void loadButtonMouseEntered(MouseEvent evt) {
        loadButton.setBackground(new java.awt.Color(250, 128, 114));
        loadButton.setForeground(new java.awt.Color(0,0,0));
    }                                       

    private void loadButtonMouseExited(MouseEvent evt) {
        loadButton.setBackground(new java.awt.Color(0,0,0));
        loadButton.setForeground(new java.awt.Color(255,255,255));
    }                                      

    private void clearButtonMouseEntered(MouseEvent evt) {                                         
        clearButton.setBackground(new java.awt.Color(250, 128, 114));
        clearButton.setForeground(new java.awt.Color(0,0,0));
    }                                        

    private void clearButtonMouseExited(MouseEvent evt) {
       clearButton.setBackground(new java.awt.Color(0,0,0));
       clearButton.setForeground(new java.awt.Color(255,255,255));
    }                                       

    private void inspectButtonMouseEntered(MouseEvent evt) {
        inspectButton.setBackground(new java.awt.Color(250, 128, 114));
        inspectButton.setForeground(new java.awt.Color(0, 0, 0));
    }                                          

    private void inspectButtonMouseExited(MouseEvent evt) {
        inspectButton.setBackground(inspectMode ? new java.awt.Color(34, 139, 34) : new java.awt.Color(0, 0, 0));
        inspectButton.setForeground(new java.awt.Color(255, 255, 255));
    }                                         

    private void formWindowOpened(WindowEvent evt) {
        Image titleIcon = Toolkit.getDefaultToolkit().getImage(constants.userDir+"/icons/bolt.jpg");
        this.setIconImage(titleIcon);
    }                                 
    
    private void loadUrl(String url) {
        CompletableFuture.runAsync(() -> {
            try {
                driver.get(url);
                Thread.sleep(2000);
                SwingUtilities.invokeLater(() -> {
                    // Set outputArea and scrollPane background to black and text color to white
                    outputArea.setOpaque(true);
                    outputArea.setBackground(new Color(0, 0, 0)); // Reinforce black background
                    outputArea.setForeground(new Color(255, 255, 255)); // Reinforce white foreground
                    scrollPane.setBackground(new Color(0, 0, 0));
                    scrollPane.setForeground(new Color(255, 255, 255));
                    scrollPane.getViewport().setBackground(new Color(0, 0, 0));
                    StyledDocument doc = outputArea.getStyledDocument();
                    SimpleAttributeSet attrs = new SimpleAttributeSet();
                    String devanagariFont = getAvailableDevanagariFont();
                    StyleConstants.setFontFamily(attrs, devanagariFont);
                    StyleConstants.setFontSize(attrs, 14);
                    doc.setCharacterAttributes(0, doc.getLength(), attrs, true);
                    
                    appendToOutputArea("Loaded URL: " + url + "\n");
                    loadButton.setText("Load URL");
                    loadButton.setEnabled(true);
                    inspectButton.setEnabled(true);
                    clearButton.setEnabled(true);
                });
                System.out.println("Loaded URL: " + url);
                if (inspectMode) {
                    inspectMode = false;
                    inspectButton.setBackground(new Color(0, 0, 0));
                    inspectButton.setForeground(new Color(255, 255, 255));
                    SwingUtilities.invokeLater(() -> {
                        appendToOutputArea("\nInspect Mode: Disabled\n");
                        loadButton.setText("Load URL");
                        loadButton.setEnabled(true);
                        inspectButton.setEnabled(true);
                        clearButton.setEnabled(true);
                    });
                    toggleInspectMode(false);
                }
            } catch (Exception ex) {
                SwingUtilities.invokeLater(() -> {
                    appendToOutputArea("Error loading URL: " + ex.getMessage() + "\n");
                    loadButton.setText("Load URL");
                    loadButton.setEnabled(true);
                    inspectButton.setEnabled(true);
                    clearButton.setEnabled(true);
                });
                System.out.println("Error loading URL: " + ex.getMessage());
                ex.printStackTrace();
            }
        });
    }
    
    private void appendToOutputArea(String text) {
        SwingUtilities.invokeLater(() -> {
            try {
                StyledDocument doc = outputArea.getStyledDocument();
                SimpleAttributeSet attrs = new SimpleAttributeSet();
                String devanagariFont = getAvailableDevanagariFont();
                StyleConstants.setFontFamily(attrs, devanagariFont);
                StyleConstants.setFontSize(attrs, 14);
                System.out.println("Appending text: " + text); // Debug the raw text
                doc.insertString(doc.getLength(), text, attrs);
                outputArea.setCaretPosition(doc.getLength());
                outputArea.setBackground(new Color(0, 0, 0)); // Reinforce black background
                outputArea.setForeground(new Color(255, 255, 255)); // Reinforce white foreground
            } catch (BadLocationException e) {
                System.out.println("Error appending to outputArea: " + e.getMessage());
            }
        });
    }
    
    private void toggleInspectMode(boolean enable) {
        System.out.println("Toggling Inspect Mode: " + enable);
        capturing = enable;
        if (!enable) {
            try {
                JavascriptExecutor js = (JavascriptExecutor) driver;
                js.executeScript(
                    "if (window.elementCapture) {" +
                    "  document.removeEventListener('click', window.elementCapture, { capture: true });" +
                    "  document.removeEventListener('mouseover', window.elementHover, { capture: true });" +
                    "  document.removeEventListener('mouseout', window.elementHoverOut, { capture: true });" +
                    "  window.elementCapture = null;" +
                    "  window.elementHover = null;" +
                    "  window.elementHoverOut = null;" +
                    "  window.elementDetails = null;" +
                    "  document.body.style.removeProperty('pointer-events');" +
                    "  console.log('Inspect mode disabled, all listeners and styles removed');" +
                    "}"
                );
                System.out.println("JavaScript listeners cleared and normal interaction restored");
            } catch (Exception ex) {
                System.out.println("Error clearing JavaScript listeners: " + ex.getMessage());
                ex.printStackTrace();
                appendToOutputArea("Error clearing listeners: " + ex.getMessage() + "\n");
            }
            return;
        }

        CompletableFuture.runAsync(() -> {
            try {
                JavascriptExecutor js = (JavascriptExecutor) driver;
                driver.switchTo().defaultContent();
                Object initResult = js.executeScript(
                    "try {" +
                    "  console.log('Initializing listeners...');" +
                    "  window.elementDetails = null;" +
                    "  window.escapeXPathString = function(text) {" +
                    "    try {" +
                    "      if (!text) return '';" +
                    "      return text.replace(/\"/g, '\\\\\"');" +
                    "    } catch (err) {" +
                    "      console.error('escapeXPathString error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.hasSpacesOrNewlines = function(value) {" +
                    "    try {" +
                    "      if (!value) return false;" +
                    "      return /^\\s|\\s$|[\\n\\r]/.test(value);" +
                    "    } catch (err) {" +
                    "      console.error('hasSpacesOrNewlines error: ' + err.message);" +
                    "      return false;" +
                    "    }" +
                    "  };" +
                    "  window.normalizeText = function(text) {" +
                    "    try {" +
                    "      if (!text) return '';" +
                    "      return text.replace(/[\\n\\r]+/g, ' ').replace(/\\s+/g, ' ').trim();" +
                    "    } catch (err) {" +
                    "      console.error('normalizeText error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.getAttributeLengthExcludingSpaces = function(value) {" +
                    "    try {" +
                    "      if (!value) return 0;" +
                    "      return value.replace(/\\s/g, '').length;" +
                    "    } catch (err) {" +
                    "      console.error('getAttributeLengthExcludingSpaces error: ' + err.message);" +
                    "      return 0;" +
                    "    }" +
                    "  };" +
                    "  window.getValueUpToLastSpace = function(value, maxLength) {" +
                    "    try {" +
                    "      if (!value) return '';" +
                    "      if (value.length <= maxLength) return value.trim();" +
                    "      var truncated = value.substring(0, maxLength);" +
                    "      var lastSpaceIndex = truncated.lastIndexOf(' ');" +
                    "      if (lastSpaceIndex === -1) return truncated.trim();" +
                    "      return truncated.substring(0, lastSpaceIndex).trim();" +
                    "    } catch (err) {" +
                    "      console.error('getValueUpToLastSpace error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.getValueUpToFirstSpace = function(value) {" +
                    "    try {" +
                    "      if (!value) return '';" +
                    "      var spaceIndex = value.indexOf(' ');" +
                    "      if (spaceIndex === -1) return value.trim();" +
                    "      return value.substring(0, spaceIndex).trim();" +
                    "    } catch (err) {" +
                    "      console.error('getValueUpToFirstSpace error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.getCssSelector = function(element) {" +
                    "    try {" +
                    "      if (!element || !element.tagName) return '';" +
                    "      var path = [];" +
                    "      var current = element;" +
                    "      while (current && current.nodeType === 1) {" +
                    "        var selector = current.tagName.toLowerCase();" +
                    "        var siblings = current.parentNode ? Array.from(current.parentNode.children).filter(function(child) {" +
                    "          return child.tagName === current.tagName;" +
                    "        }) : [];" +
                    "        if (siblings.length > 1) {" +
                    "          var index = siblings.indexOf(current) + 1;" +
                    "          selector += ':nth-of-type(' + index + ')';" +
                    "        }" +
                    "        path.unshift(selector);" +
                    "        current = current.parentNode;" +
                    "        if (path.length > 3) break;" +
                    "      }" +
                    "      return path.join(' > ') || element.tagName.toLowerCase();" +
                    "    } catch (err) {" +
                    "      console.error('getCssSelector error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.getAbsoluteXPath = function(element) {" +
                    "    try {" +
                    "      if (!element || !element.tagName) return '';" +
                    "      var paths = [];" +
                    "      var current = element;" +
                    "      while (current && current.nodeType === 1 && current !== document.documentElement) {" +
                    "        var index = 0;" +
                    "        var siblings = current.parentNode ? Array.from(current.parentNode.childNodes).filter(function(node) {" +
                    "          return node.nodeType === 1 && node.tagName === current.tagName;" +
                    "        }) : [];" +
                    "        for (var i = 0; i < siblings.length; i++) {" +
                    "          if (siblings[i] === current) {" +
                    "            index = i + 1;" +
                    "            break;" +
                    "          }" +
                    "        }" +
                    "        var tag = current.tagName.toLowerCase();" +
                    "        var isSvg = current.namespaceURI === 'http://www.w3.org/2000/svg';" +
                    "        var segment = isSvg ? '*[local-name()=\"' + tag + '\"]': tag;" +
                    "        segment = index > 0 ? segment + '[' + index + ']' : segment;" +
                    "        paths.unshift(segment);" +
                    "        current = current.parentNode;" +
                    "      }" +
                    "      return paths.length ? '/html' + (paths.length ? '/' + paths.join('/') : '') : '';" +
                    "    } catch (err) {" +
                    "      console.error('getAbsoluteXPath error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.findLastTextDescendant = function(element) {" +
                    "    try {" +
                    "      for (var i = element.children.length - 1; i >= 0; i--) {" +
                    "        var childLast = window.findLastTextDescendant(element.children[i]);" +
                    "        if (childLast) {" +
                    "          return childLast;" +
                    "        }" +
                    "      }" +
                    "      var directText = Array.from(element.childNodes).filter(n => n.nodeType === 3).map(n => n.nodeValue.trim()).join(' ').trim();" +
                    "      if (directText.length > 0) {" +
                    "        return {el: element, text: window.normalizeText(directText)};" +
                    "      }" +
                    "      return null;" +
                    "    } catch (err) {" +
                    "      console.error('findLastTextDescendant error: ' + err.message);" +
                    "      return null;" +
                    "    }" +
                    "  };" +
                    "  window.getRelativeXPath = function(element) {" +
                    "    try {" +
                    "      if (!element || !element.tagName) return '';" +
                    "      var tag = element.tagName.toLowerCase();" +
                    "      var isSvg = element.namespaceURI === 'http://www.w3.org/2000/svg';" +
                    "      var predicates = [];" +
                    "      if (isSvg) {" +
                    "        predicates.push('local-name()=\"' + tag + '\"');" +
                    "        var attrsToCheck = ['id', 'name', 'value', 'data-icon', 'aria-label', 'role', 'class', 'd', 'transform', 'x', 'y', 'width', 'height', 'viewBox'];" +
                    "        var longAttr = null;" +
                    "        var longAttrName = null;" +
                    "        for (var i = 0; i < attrsToCheck.length; i++) {" +
                    "          var attr = attrsToCheck[i];" +
                    "          var attrValue = element.getAttribute(attr);" +
                    "          if (attrValue && attrValue.trim()) {" +
                    "            var trimmedValue = attrValue.trim();" +
                    "            var noSpacesLength = window.getAttributeLengthExcludingSpaces(trimmedValue);" +
                    "            if (noSpacesLength > 100) {" +
                    "              longAttr = window.getValueUpToLastSpace(trimmedValue, 100);" +
                    "              longAttrName = attr;" +
                    "              break;" +
                    "            }" +
                    "          }" +
                    "        }" +
                    "        if (longAttrName && longAttr) {" +
                    "          var escapedValue = window.escapeXPathString(longAttr);" +
                    "          predicates.push('contains(@*[local-name()=\"' + longAttrName + '\"], \"' + escapedValue + '\")');" +
                    "        } else {" +
                    "          for (var i = 0; i < attrsToCheck.length; i++) {" +
                    "            var attr = attrsToCheck[i];" +
                    "            var attrValue = element.getAttribute(attr);" +
                    "            if (attrValue && attrValue.trim()) {" +
                    "              var trimmedValue = attrValue.trim();" +
                    "              var escapedValue = window.escapeXPathString(trimmedValue);" +
                    "              predicates.push('contains(@*[local-name()=\"' + attr + '\"], \"' + escapedValue + '\")');" +
                    "              break;" +
                    "            }" +
                    "          }" +
                    "        }" +
                    "        if (element.getAttributeNS && element.getAttributeNS('http://www.w3.org/1999/xlink', 'href') && element.getAttributeNS('http://www.w3.org/1999/xlink', 'href').trim()) {" +
                    "          var hrefValue = element.getAttributeNS('http://www.w3.org/1999/xlink', 'href').trim();" +
                    "          var noSpacesLength = window.getAttributeLengthExcludingSpaces(hrefValue);" +
                    "          var escapedHref = window.escapeXPathString(noSpacesLength > 100 ? window.getValueUpToLastSpace(hrefValue, 100) : hrefValue);" +
                    "          predicates.push('contains(@*[local-name()=\"href\" and namespace-uri()=\"http://www.w3.org/1999/xlink\"], \"' + escapedHref + '\")');" +
                    "        }" +
                    "        var text = '';" +
                    "        var textElement = null;" +
                    "        var directText = '';" +
                    "        for (var i = 0; i < element.childNodes.length; i++) {" +
                    "          var child = element.childNodes[i];" +
                    "          if (child.nodeType === 3) {" +
                    "            directText += child.nodeValue;" +
                    "          } else if (child.nodeType === 1) {" +
                    "            var childText = window.normalizeText(child.textContent).trim();" +
                    "            if (childText.length > 0) {" +
                    "              if (child.tagName.toLowerCase() === 'span') {" +
                    "                text = childText;" +
                    "                textElement = child;" +
                    "                break;" +
                    "              } else if (!textElement) {" +
                    "                text = childText;" +
                    "                textElement = child;" +
                    "              }" +
                    "            }" +
                    "          }" +
                    "        }" +
                    "        var normalizedDirectText = window.normalizeText(directText).trim();" +
                    "        if (normalizedDirectText.length > 0 && !textElement) {" +
                    "          text = normalizedDirectText;" +
                    "        }" +
                    "        var xpath = '//*';" +
                    "        if (predicates.length > 0) {" +
                    "          xpath += '[' + predicates.join(' and ') + ']';" +
                    "        } else {" +
                    "          xpath += '[local-name()=\"' + tag + '\"]';" +
                    "        }" +
                    "        if (text.length > 0 && textElement) {" +
                    "          var childTag = textElement.tagName.toLowerCase();" +
                    "          var isChildSvg = textElement.namespaceURI === 'http://www.w3.org/2000/svg';" +
                    "          xpath += '//' + (isChildSvg ? '*' : childTag);" +
                    "          var childPredicates = [];" +
                    "          if (isChildSvg) {" +
                    "            childPredicates.push('local-name()=\"' + childTag + '\"');" +
                    "          }" +
                    "          childPredicates.push('contains(normalize-space(text()), \"' + window.escapeXPathString(text) + '\")');" +
                    "          if (childPredicates.length > 0) {" +
                    "            xpath += '[' + childPredicates.join(' and ') + ']';" +
                    "          }" +
                    "        } else if (text.length > 0) {" +
                    "          predicates.push('contains(normalize-space(text()), \"' + window.escapeXPathString(text) + '\")');" +
                    "          xpath = '//*' + '[' + predicates.join(' and ') + ']';" +
                    "        }" +
                    "        if (isSvg) {" +
                    "          var parentPredicates = [];" +
                    "          var parent = element.parentNode;" +
                    "          if (parent && parent.nodeType === 1) {" +
                    "            var parentTag = parent.tagName.toLowerCase();" +
                    "            var parentIsSvg = parent.namespaceURI === 'http://www.w3.org/2000/svg';" +
                    "            if (parentIsSvg) {" +
                    "              parentPredicates.push('local-name()=\"' + parentTag + '\"');" +
                    "            }" +
                    "            for (var i = 0; i < attrsToCheck.length; i++) {" +
                    "              var attr = attrsToCheck[i];" +
                    "              var attrValue = parent.getAttribute(attr);" +
                    "              if (attrValue && attrValue.trim()) {" +
                    "                var trimmedValue = attrValue.trim();" +
                    "                var noSpacesLength = window.getAttributeLengthExcludingSpaces(trimmedValue);" +
                    "                var escapedValue = window.escapeXPathString(noSpacesLength > 100 ? window.getValueUpToFirstSpace(trimmedValue) : trimmedValue);" +
                    "                if (parentIsSvg) {" +
                    "                  parentPredicates.push('contains(@*[local-name()=\"' + attr + '\"], \"' + escapedValue + '\")');" +
                    "                } else {" +
                    "                  parentPredicates.push('contains(@' + attr + ', \"' + escapedValue + '\")');" +
                    "                }" +
                    "                break;" +
                    "              }" +
                    "            }" +
                    "            if (parent.getAttributeNS && parent.getAttributeNS('http://www.w3.org/1999/xlink', 'href') && parent.getAttributeNS('http://www.w3.org/1999/xlink', 'href').trim()) {" +
                    "              var parentHrefValue = parent.getAttributeNS('http://www.w3.org/1999/xlink', 'href').trim();" +
                    "              var noSpacesLength = window.getAttributeLengthExcludingSpaces(parentHrefValue);" +
                    "              var escapedHref = window.escapeXPathString(noSpacesLength > 100 ? window.getValueUpToFirstSpace(parentHrefValue) : parentHrefValue);" +
                    "              parentPredicates.push('contains(@*[local-name()=\"href\" and namespace-uri()=\"http://www.w3.org/1999/xlink\"], \"' + escapedHref + '\")');" +
                    "            }" +
                    "            var parentXPath = '//' + (parentIsSvg ? '*' : parentTag);" +
                    "            if (parentPredicates.length > 0) {" +
                    "              parentXPath += '[' + parentPredicates.join(' and ') + ']';" +
                    "            } else if (parentIsSvg) {" +
                    "              parentXPath += '[local-name()=\"' + parentTag + '\"]';" +
                    "            }" +
                    "            xpath = parentXPath + '//' + xpath;" +
                    "          }" +
                    "        }" +
                    "      } else {" +
                    "        var lastTextDescendant = window.findLastTextDescendant(element);" +
                    "        var text = '';" +
                    "        var textElement = null;" +
                    "        if (lastTextDescendant) {" +
                    "          text = lastTextDescendant.text;" +
                    "          textElement = lastTextDescendant.el;" +
                    "        }" +
                    "        var usedText = text.length > 0;" +
                    "        var xpath = '';" +
                    "        var predicates = [];" +
                    "        if (usedText && !window.hasSpacesOrNewlines(text)) {" +
                    "          var childTag = textElement.tagName.toLowerCase();" +
                    "          xpath = '//' + childTag;" +
                    "          predicates.push('normalize-space(text())=\"' + window.escapeXPathString(text) + '\"');" +
                    "          xpath += '[' + predicates.join(' and ') + ']';" +
                    "        } else {" +
                    "          var foundAttr = false;" +
                    "          var attrValue = element.getAttribute('id');" +
                    "          if (attrValue && attrValue.trim()) {" +
                    "            var trimmedValue = attrValue.trim();" +
                    "            var noSpacesLength = window.getAttributeLengthExcludingSpaces(trimmedValue);" +
                    "            var valueToUse = noSpacesLength > 100 ? window.getValueUpToFirstSpace(trimmedValue) : trimmedValue;" +
                    "            predicates.push('contains(@id, \"' + window.escapeXPathString(valueToUse) + '\")');" +
                    "            foundAttr = true;" +
                    "          }" +
                    "          if (!foundAttr) {" +
                    "            var priorAttrs = ['aria-label', 'name', 'value'];" +
                    "            for (var i = 0; i < priorAttrs.length; i++) {" +
                    "              var attr = priorAttrs[i];" +
                    "              attrValue = element.getAttribute(attr);" +
                    "              if (attrValue && attrValue.trim()) {" +
                    "                trimmedValue = attrValue.trim();" +
                    "                noSpacesLength = window.getAttributeLengthExcludingSpaces(trimmedValue);" +
                    "                valueToUse = noSpacesLength > 100 ? window.getValueUpToFirstSpace(trimmedValue) : trimmedValue;" +
                    "                predicates.push('contains(@' + attr + ', \"' + window.escapeXPathString(valueToUse) + '\")');" +
                    "                foundAttr = true;" +
                    "                break;" +
                    "              }" +
                    "            }" +
                    "          }" +
                    "          if (!foundAttr) {" +
                    "            attrValue = element.getAttribute('class');" +
                    "            if (attrValue && attrValue.trim()) {" +
                    "              trimmedValue = attrValue.trim();" +
                    "              noSpacesLength = window.getAttributeLengthExcludingSpaces(trimmedValue);" +
                    "              valueToUse = noSpacesLength > 100 ? window.getValueUpToFirstSpace(trimmedValue) : trimmedValue;" +
                    "              predicates.push('contains(@class, \"' + window.escapeXPathString(valueToUse) + '\")');" +
                    "              foundAttr = true;" +
                    "            }" +
                    "          }" +
                    "          if (!foundAttr) {" +
                    "            var allAttrs = element.attributes;" +
                    "            for (var i = 0; i < allAttrs.length; i++) {" +
                    "              var attr = allAttrs[i].name;" +
                    "              if (['id', 'aria-label', 'name', 'value', 'class'].includes(attr)) continue;" +
                    "              var value = allAttrs[i].value.trim();" +
                    "              if (value) {" +
                    "                var query = '//' + tag + '[@' + attr + '=\"' + window.escapeXPathString(value) + '\"]';" +
                    "                var result = document.evaluate(query, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);" +
                    "                if (result.snapshotLength === 1) {" +
                    "                  predicates.push('@' + attr + '=\"' + window.escapeXPathString(value) + '\"');" +
                    "                  foundAttr = true;" +
                    "                  break;" +
                    "                }" +
                    "              }" +
                    "            }" +
                    "          }" +
                    "          if (element.getAttributeNS && element.getAttributeNS('http://www.w3.org/1999/xlink', 'href') && element.getAttributeNS('http://www.w3.org/1999/xlink', 'href').trim()) {" +
                    "            var hrefValue = element.getAttributeNS('http://www.w3.org/1999/xlink', 'href').trim();" +
                    "            var noSpacesLength = window.getAttributeLengthExcludingSpaces(hrefValue);" +
                    "            var escapedHref = window.escapeXPathString(noSpacesLength > 100 ? window.getValueUpToFirstSpace(hrefValue) : hrefValue);" +
                    "            predicates.push('contains(@*[local-name()=\"href\" and namespace-uri()=\"http://www.w3.org/1999/xlink\"], \"' + escapedHref + '\")');" +
                    "            foundAttr = true;" +
                    "          }" +
                    "          xpath = '//' + tag;" +
                    "          if (predicates.length > 0) {" +
                    "            xpath += '[' + predicates.join(' and ') + ']';" +
                    "          }" +
                    "        }" +
                    "        var result = document.evaluate(xpath, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);" +
                    "        if (result.snapshotLength > 1) {" +
                    "          var allAttrs = element.attributes;" +
                    "          for (var i = 0; i < allAttrs.length; i++) {" +
                    "            var attr = allAttrs[i].name;" +
                    "            if (['id', 'aria-label', 'name', 'value', 'class'].includes(attr)) continue;" +
                    "            var value = allAttrs[i].value.trim();" +
                    "            if (value) {" +
                    "              var testXPath = xpath + '[@' + attr + '=\"' + window.escapeXPathString(value) + '\"]';" +
                    "              var testResult = document.evaluate(testXPath, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);" +
                    "              if (testResult.snapshotLength === 1) {" +
                    "                xpath = testXPath;" +
                    "                break;" +
                    "              }" +
                    "            }" +
                    "          }" +
                    "        }" +
                    "        if (result.snapshotLength > 1) {" +
                    "          var parent = element.parentNode;" +
                    "          if (parent && parent.nodeType === 1) {" +
                    "            var parentTag = parent.tagName.toLowerCase();" +
                    "            var parentPredicates = [];" +
                    "            var parentAttrs = parent.attributes;" +
                    "            for (var i = 0; i < parentAttrs.length; i++) {" +
                    "              var attr = parentAttrs[i].name;" +
                    "              var value = parentAttrs[i].value.trim();" +
                    "              if (value) {" +
                    "                var noSpacesLength = window.getAttributeLengthExcludingSpaces(value);" +
                    "                var valueToUse = noSpacesLength > 100 ? window.getValueUpToFirstSpace(value) : value;" +
                    "                parentPredicates.push('contains(@' + attr + ', \"' + window.escapeXPathString(valueToUse) + '\")');" +
                    "                var parentXPath = '//' + parentTag + '[' + parentPredicates.join(' and ') + ']';" +
                    "                var combinedXPath = parentXPath + xpath;" +
                    "                var combinedResult = document.evaluate(combinedXPath, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);" +
                    "                if (combinedResult.snapshotLength === 1) {" +
                    "                  xpath = combinedXPath;" +
                    "                  break;" +
                    "                }" +
                    "              }" +
                    "            }" +
                    "            if (parentPredicates.length === 0) {" +
                    "              var parentXPath = '//' + parentTag;" +
                    "              xpath = parentXPath + xpath;" +
                    "            }" +
                    "          }" +
                    "        }" +
                    "      }" +
                    "      console.log('Generated relativeXPath: ' + xpath);" +
                    "      return xpath;" +
                    "    } catch (err) {" +
                    "      console.error('getRelativeXPath error: ' + err.message);" +
                    "      return '';" +
                    "    }" +
                    "  };" +
                    "  window.elementCapture = function(e) {" +
                    "    try {" +
                    "      e.preventDefault();" +
                    "      e.stopPropagation();" +
                    "      var el = e.target;" +
                    "      var normalizedText = el.textContent ? window.normalizeText(el.textContent.substring(0, 50)) : '';" +
                    "      var details = {" +
                    "        tagName: el.tagName ? el.tagName.toLowerCase() : ''," +
                    "        text: normalizedText," +
                    "        id: el.id || ''," +
                    "        class: el.className || ''," +
                    "        cssSelector: window.getCssSelector(el)," +
                    "        absoluteXPath: window.getAbsoluteXPath(el)," +
                    "        relativeXPath: window.getRelativeXPath(el)" +
                    "      };" +
                    "      console.log('elementCapture details: ' + JSON.stringify(details));" +
                    "      window.elementDetails = details;" +
                    "      return JSON.stringify(details);" +
                    "    } catch (err) {" +
                    "      console.error('elementCapture error: ' + err.message);" +
                    "      return 'Error: ' + err.message;" +
                    "    }" +
                    "  };" +
                    "  window.elementHover = function(e) {" +
                    "    try {" +
                    "      e.target.style.outline = '2px solid red';" +
                    "    } catch (err) {" +
                    "      console.error('elementHover error: ' + err.message);" +
                    "    }" +
                    "  };" +
                    "  window.elementHoverOut = function(e) {" +
                    "    try {" +
                    "      e.target.style.outline = '';" +
                    "    } catch (err) {" +
                    "      console.error('elementHoverOut error: ' + err.message);" +
                    "    }" +
                    "  };" +
                    "  window.checkListeners = function() {" +
                    "    try {" +
                    "      return !!window.elementCapture;" +
                    "    } catch (err) {" +
                    "      console.error('checkListeners error: ' + err.message);" +
                    "      return false;" +
                    "    }" +
                    "  };" +
                    "  document.removeEventListener('click', window.elementCapture);" +
                    "  document.removeEventListener('mouseover', window.elementHover);" +
                    "  document.removeEventListener('mouseout', window.elementHoverOut);" +
                    "  document.addEventListener('click', window.elementCapture, { capture: true, passive: false });" +
                    "  document.addEventListener('mouseover', window.elementHover, { capture: true, passive: true });" +
                    "  document.addEventListener('mouseout', window.elementHoverOut, { capture: true, passive: true });" +
                    "  setTimeout(function() {" +
                    "    window.checkListeners();" +
                    "  }, 500);" +
                    "  console.log('Listeners setup complete');" +
                    "  return { status: 'Listeners setup initiated' };" +
                    "} catch (err) {" +
                    "  console.error('Initialization error: ' + err.message);" +
                    "  return { status: 'Error: ' + err.message };" +
                    "}"
                );
                System.out.println("initResult: " + (initResult != null ? initResult.toString() : "null"));
                if (initResult == null || initResult.toString().contains("Error:")) {
                    String errorMsg = initResult != null ? initResult.toString() : "Initialization result is null";
                    appendToOutputArea("Failed to initialize listeners: " + errorMsg + "\n");
                    return;
                }

                if (initResult instanceof HashMap) {
                    HashMap<String, Object> resultMap = (HashMap<String, Object>) initResult;
                    String status = (String) resultMap.get("status");
                    System.out.println("Initialization status: " + status);
                    if (!"Listeners setup initiated".equals(status)) {
                        appendToOutputArea("Failed to initialize listeners: " + status + "\n");
                        return;
                    }
                }

                Thread.sleep(1000);
                Object listenerStatus = js.executeScript("return window.checkListeners ? window.checkListeners() : false;");
                System.out.println("Listener status after setup: " + listenerStatus);
                if (listenerStatus instanceof Boolean && !(Boolean) listenerStatus) {
                    appendToOutputArea("Error: Listeners not attached properly\n");
                    return;
                }

                while (capturing && driver != null) {
                    try {
                        Object result = js.executeScript(
                            "try {" +
                            "  console.log('Polling elementDetails...');" +
                            "  var result = window.elementDetails;" +
                            "  if (result) {" +
                            "    window.elementDetails = null;" +
                            "    return { details: JSON.stringify(result) };" +
                            "  }" +
                            "  return { details: null };" +
                            "} catch (err) {" +
                            "  console.error('Poll error: ' + err.message);" +
                            "  return { details: 'Error: ' + err.message };" +
                            "}"
                        );
                        String details = null;
                        if (result instanceof HashMap) {
                            HashMap<String, Object> resultMap = (HashMap<String, Object>) result;
                            details = (String) resultMap.get("details");
                        }
                        final String finalDetails = details;
                        if (finalDetails != null && !finalDetails.isEmpty() && !finalDetails.startsWith("Error:") && !finalDetails.equals("null")) {
                            System.out.println("Raw JSON details: " + finalDetails); // Debug raw JSON
                            String parsedDetails = extractor.extractElementDetails(finalDetails);
                            System.out.println("Parsed details: " + parsedDetails); // Debug parsed details
                            if (parsedDetails != null && !parsedDetails.trim().isEmpty() && !parsedDetails.contains("No valid element details parsed")) {
                                String elementId = "Element_" + System.currentTimeMillis();
                                extractor.storeInRepository(elementId, parsedDetails);
                                appendElementDetails(elementId, parsedDetails, finalDetails);
                            } else {
                                System.out.println("No valid details parsed: " + parsedDetails);
                                appendToOutputArea("Element Details: No valid element details parsed: " + parsedDetails + "\n");
                            }
                        } else if (finalDetails != null && finalDetails.startsWith("Error:")) {
                            System.out.println("JavaScript error: " + finalDetails);
                            appendToOutputArea("JavaScript error: " + finalDetails + "\n");
                        }
                        Thread.sleep(500);
                    } catch (Exception ex) {
                        System.out.println("Capture error: " + ex.getMessage());
                        ex.printStackTrace();
                        appendToOutputArea("Capture error: " + ex.getMessage() + "\n");
                    }
                }
            } catch (Exception ex) {
                System.out.println("Error initializing listeners: " + ex.getMessage());
                ex.printStackTrace();
                appendToOutputArea("Error initializing listeners: " + ex.getMessage() + "\n");
            }
        });
    }
    
    private String getAvailableDevanagariFont() {
        String[] devanagariFonts = {"Mangal", "Noto Sans Devanagari", "Arial Unicode MS"};
        for (String font : devanagariFonts) {
            if (Font.getFont(font) != null) {
                System.out.println("Using font: " + font);
                return font;
            }
        }
        System.out.println("Warning: No Devanagari font found, falling back to default");
        return "Dialog"; // Fallback to system default
    }
    
    private void appendElementDetails(String elementId, String parsedDetails, String rawJsonDetails) {
        SwingUtilities.invokeLater(() -> {
            try {
                StyledDocument doc = outputArea.getStyledDocument();
                SimpleAttributeSet attrs = new SimpleAttributeSet();
                String devanagariFont = getAvailableDevanagariFont();
                StyleConstants.setFontFamily(attrs, devanagariFont);
                StyleConstants.setFontSize(attrs, 14);

                // Insert a JSeparator to mimic an HTML <hr> separator
                JSeparator separator = new JSeparator(JSeparator.HORIZONTAL);
                separator.setForeground(new Color(255, 153, 153)); // Match outputArea text color
                separator.setBackground(new Color(0, 0, 0)); // Match outputArea background
                separator.setPreferredSize(new Dimension(outputArea.getWidth() - 20, 2)); // Adjust width to fit
                Style separatorStyle = doc.addStyle("separator" + System.currentTimeMillis(), null);
                StyleConstants.setComponent(separatorStyle, separator);
                doc.insertString(doc.getLength(), "\n", attrs); // Add newline before separator
                doc.insertString(doc.getLength(), " ", separatorStyle); // Insert separator
                doc.insertString(doc.getLength(), "\nStored in repository as: " + elementId + "\nElement Details:\n", attrs);

                // Parse raw JSON to extract relativeXPath directly
                String relativeXPath = "";
                String absoluteXPath = "";
                try {
                    JSONObject json = new JSONObject(rawJsonDetails);
                    relativeXPath = json.optString("relativeXPath", "");
                    absoluteXPath = json.optString("absoluteXPath", "");
                    System.out.println("Raw relativeXPath from JSON: " + relativeXPath); // Debug raw XPath
                } catch (Exception e) {
                    System.out.println("Error parsing raw JSON: " + e.getMessage());
                    doc.insertString(doc.getLength(), "Error parsing JSON: " + e.getMessage() + "\n", attrs);
                }

                String[] lines = parsedDetails.split("\n");
                for (String line : lines) {
                    if (line.startsWith("relativeXPath:") && !relativeXPath.isEmpty()) {
                        // Use raw relativeXPath from JSON
                        CustomButton copyButton = new CustomButton("Copy", 8, 1, new Color(250, 128, 114), new Color(250, 128, 114));
                        copyButton.setFont(new Font("Arial", Font.PLAIN, 10));
                        copyButton.setMargin(new Insets(2, 4, 2, 4));
                        copyButton.setForeground(Color.WHITE);
                        String finalXPath = relativeXPath;
                        copyButton.addActionListener(e -> {
                            StringSelection selection = new StringSelection(finalXPath);
                            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                            clipboard.setContents(selection, null);
                            appendToOutputArea("Copied to clipboard: " + finalXPath + "\n");
                        });
                        CustomButton addButton = new CustomButton("Add", 8, 1, new Color(250, 128, 114), new Color(250, 128, 114));
                        addButton.setFont(new Font("Arial", Font.PLAIN, 10));
                        addButton.setMargin(new Insets(2, 4, 2, 4));
                        addButton.setForeground(Color.WHITE);
                        addButton.addActionListener(e -> {
                            appendToOutputArea("Element added to the repository\n");
                            CreateTestSuite.addWebElementToRepository(elementId, finalXPath);
                        });
                        Style buttonStyle = doc.addStyle("button" + System.currentTimeMillis(), null);
                        StyleConstants.setComponent(buttonStyle, copyButton);
                        doc.insertString(doc.getLength(), " ", buttonStyle);
                        doc.insertString(doc.getLength(), " ", attrs);
                        Style addButtonStyle = doc.addStyle("addButton" + System.currentTimeMillis(), null);
                        StyleConstants.setComponent(addButtonStyle, addButton);
                        doc.insertString(doc.getLength(), " ", addButtonStyle);
                        doc.insertString(doc.getLength(), " relativeXPath: " + relativeXPath + "\n", attrs);
                    } else if (line.startsWith("absoluteXPath:") && !absoluteXPath.isEmpty()) {
                        // Use raw absoluteXPath from JSON
                        CustomButton copyButton = new CustomButton("Copy", 8, 1, new Color(250, 128, 114), new Color(250, 128, 114));
                        copyButton.setFont(new Font("Arial", Font.PLAIN, 10));
                        copyButton.setMargin(new Insets(2, 4, 2, 4));
                        copyButton.setForeground(Color.WHITE);
                        String finalXPath = absoluteXPath;
                        copyButton.addActionListener(e -> {
                            StringSelection selection = new StringSelection(finalXPath);
                            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                            clipboard.setContents(selection, null);
                            appendToOutputArea("Copied to clipboard: " + finalXPath + "\n");
                        });
                        CustomButton addButton = new CustomButton("Add", 8, 1, new Color(250, 128, 114), new Color(250, 128, 114));
                        addButton.setFont(new Font("Arial", Font.PLAIN, 10));
                        addButton.setMargin(new Insets(2, 4, 2, 4));
                        addButton.setForeground(Color.WHITE);
                        addButton.addActionListener(e -> {
                            appendToOutputArea("Element added to the repository\n");
                            CreateTestSuite.addWebElementToRepository(elementId, finalXPath);
                        });
                        Style buttonStyle = doc.addStyle("button" + System.currentTimeMillis(), null);
                        StyleConstants.setComponent(buttonStyle, copyButton);
                        doc.insertString(doc.getLength(), " ", buttonStyle);
                        doc.insertString(doc.getLength(), " ", attrs);
                        Style addButtonStyle = doc.addStyle("addButton" + System.currentTimeMillis(), null);
                        StyleConstants.setComponent(addButtonStyle, addButton);
                        doc.insertString(doc.getLength(), " ", addButtonStyle);
                        doc.insertString(doc.getLength(), " absoluteXPath: " + absoluteXPath + "\n", attrs);
                    } else {
                        doc.insertString(doc.getLength(), line + "\n", attrs);
                    }
                }
                outputArea.setCaretPosition(doc.getLength());
                outputArea.setBackground(new Color(0, 0, 0)); // Reinforce black background
                outputArea.setForeground(new Color(255, 255, 255)); // Reinforce white foreground
            } catch (BadLocationException e) {
                System.out.println("Error appending element details: " + e.getMessage());
            }
        });
    }

    public static class CustomButton extends JButton {
        protected Color defaultColor = Color.BLACK;
        protected Color hoverColor = new Color(250, 128, 114);
        protected Color disabledColor = new Color(50, 50, 50);
        protected Color borderColor = null;
        protected Color borderHoverColor = null;
        protected boolean isHovered = false;
        protected boolean isDisabled = false;
        private int arc = 8;
        private int shadowOffset = 1;
        
        public CustomButton(String text) {
            this(text, 12, 1, null, null);
        }

        public CustomButton(String text, int arc, int shadowOffset) {
            this(text, arc, shadowOffset, null, null);
        }

        public CustomButton(String text, int arc, int shadowOffset, Color borderColor, Color borderHoverColor) {
            super(text);
            this.arc = arc;
            this.shadowOffset = shadowOffset;
            this.borderColor = borderColor;
            this.borderHoverColor = borderHoverColor;
            setOpaque(false);
            setContentAreaFilled(false);
            setBorderPainted(false);
            setFocusPainted(false);
            setForeground(Color.WHITE);
            setFont(new Font("Arial", Font.BOLD, 12));
            setMargin(new Insets(4, 10, 4, 10));
            setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor to pointer
            addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    isHovered = true;
                    repaint();
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    isHovered = false;
                    repaint();
                }
            });
        }

        public void setDisabled(boolean disabled) {
            this.isDisabled = disabled;
            repaint();
        }

        public void setBackgroundColor(Color color) {
            this.defaultColor = color;
            repaint();
        }

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(new Color(0, 0, 0, 50));
            g2.fill(new RoundRectangle2D.Float(shadowOffset, shadowOffset, getWidth() - shadowOffset, getHeight() - shadowOffset, arc, arc));
            if (isDisabled || !isEnabled()) {
                g2.setColor(isHovered ? disabledColor.brighter() : disabledColor);
            } else {
                g2.setColor(isHovered ? hoverColor : defaultColor);
            }
            g2.fill(new RoundRectangle2D.Float(0, 0, getWidth() - shadowOffset, getHeight() - shadowOffset, arc, arc));
            if (borderColor != null) {
                g2.setColor(isHovered && borderHoverColor != null ? borderHoverColor : borderColor);
                g2.setStroke(new BasicStroke(1.5f));
                g2.draw(new RoundRectangle2D.Float(0, 0, getWidth() - shadowOffset, getHeight() - shadowOffset, arc, arc));
            }
            super.paintComponent(g);
            g2.dispose();
        }
    }
    
    private boolean isBrowserOpen() {
        if (driver == null) {
            return false;
        }
        try {
            driver.getWindowHandle();
            return true;
        } catch (Exception e) {
            System.out.println("Browser window is closed or unavailable: " + e.getMessage());
            return false;
        }
    }
    
    private void startBrowserPolling() {
        CompletableFuture.runAsync(() -> {
            while (polling.get() && driver != null) {
                try {
                    if (!isBrowserOpen()) {
                        System.out.println("Browser window closed, closing JFrame");
                        SwingUtilities.invokeLater(() -> {
                            appendToOutputArea("Browser window closed, shutting down application\n");
                            if (inspectMode) {
                                toggleInspectMode(false);
                            }
                            this.dispose();
                            polling.set(false);
                        });
                        break;
                    }
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    System.out.println("Browser polling interrupted: " + e.getMessage());
                    break;
                }
            }
        });
    }

    @Override
    public void dispose() {
        polling.set(false); // Stop the polling thread
        if (driver != null) {
            try {
                driver.quit(); // Close the WebDriver
                System.out.println("WebDriver closed successfully");
                appendToOutputArea("WebDriver closed\n");
            } catch (Exception e) {
                System.out.println("Error closing WebDriver: " + e.getMessage());
                appendToOutputArea("Error closing WebDriver: " + e.getMessage() + "\n");
            }
            driver = null; // Nullify the driver reference
        }
        super.dispose(); // Call the parent dispose method
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WebElementInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WebElementInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WebElementInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WebElementInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //System.setProperty("java.awt.headless", "false");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WebElementInspector().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    public JButton clearButton;
    public JButton inspectButton;
    public JButton loadButton;
    public JTextPane outputArea;
    public JScrollPane scrollPane;
    public JTextField urlField;
    public JLabel urlLabel;
    // End of variables declaration                   

    private void contentEquals(String testId) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}